### ISSUE TITLE
suggestion: Intelligence

### ISSUE THREAD

**Issue by SondreBakken** [KillahPotatoes/KP-Liberation#165]
An interesting aspect of the game is intelligence points. These havent really recieved a lot of attention and I think there is a lot of potential around it. Currently the system is really simple, you interrogate POWs or pick up intel (laptops or documents) and you can trade points for special missions that will lower the opfors aggressiveness. 

At some points the current intelligence system actually succeeds in creating some interesting gameplay. When the Opfor aggressiveness is really high, and I am at a point where I have no chance to take sectors because of heavy reinforcements I would have to storm smaller sectors, grab prisoners and get out quickly. This requires planning, synchronisation and stealth. This is the closest I have gotten to feeling like I am doing specOps in Liberation. I think the intelligence system could generate more moments like this with an total overhaul like the resource system. I also think this should be tightly knit with the sidemission improvements I mentioned (randomly spawning and time critical)

So here are some thoughts and suggestions that I hope people will expand upon:

1.1 Intelligence is converted to percentages. This is to be able to tell whether your intelligence level is good or bad.

1.2 Intelligence deteriorate. Intelligence needs to be fresh. So intelligence gathered from POWS, items and certain missions deteriorate. While some type gathering  intelligence does not because it provides continuous stream of intelligence. See 1.5 radiotowers.

1.3 Higher levels of intelligence gives certain perks: (Examples/To be expanded)
Over 60%: 
- You will be warned whenever opFor is planning to take back a sector

Over 40%: 
- You will be warned whenever opFor is planning an attack on a FOB.
- Destroy enemy FOBS missions appear. (These can be smaller temporary bases spawning close to captured sectors. If not dealth with could trigger a sector attack)

Over 20%: 
- Capture sidemission, and assasinate sidemissions will randomly appear (time critical as in: Objective is at this location, capture him or kill him before he disappears. Lowers aggressivity)

So there would be an incentive to keep your intelligence percentage as high as possible.

1.4 To capture POWs and pick up certain items for intelligence should remain in the game, but there should also be more specific ways to heighten your intelligence. 

1.5 Capturing radiotowers that covers enemy sectors could give a base intelligence. 2% per enemy sector that is covered by your radiotowers. This does not deteriorate.

1.6 A mission type that occurs when your intelligence level is over a certain percentage is: Certain person is in certain area. You can choose what to do with this. Kill him lowers aggressivity (lowers opfor readiness, they are still mad :D ) or capture him (harder) but lowers aggressivity and gives a temporary intelligence boost.

1.7 Rescue people. the crashsite mission requires no intelligence to occur, but rescue prisoners do. Both yield intelligence.

Open for more suggestions to missions types/ways to gather intelligence. 
- Setting up listening posts
- Recon missions
- Drone missions
- Locate missions

**Comment by Wyqer** [comment]
Wow, many thanks for that well written suggestion. It's really great.

I've already a small "rework" of the intelligence system in mind.
But more in the way to provide more ways to gather these intel points. Like with observe enemy movements, ask or hire civilian informants, cooperate with guerilla forces, etc.
Maybe I can take some thoughts from this suggestion also in my ideas I already have.
Again I see the need that I write all my "brainstom", ideas, thoughts etc. down for a kind of "roadmap" or "planned and possible features" for 0.96.
I hope I'll complete something like that today or tomorrow and share it with you all, so we've all a base from which we can start thinking and state opinions or ideas.
