### ISSUE TITLE
Suggestion: Remote controlled commander that always remain in base

### ISSUE THREAD

**Issue by SondreBakken** [KillahPotatoes/KP-Liberation#267]
I am playing liberation with a small group of friends. And very often I find myself in situation where we could need some sort of backup, drone, tank or just a pick up. As it is now there is two problems. Only one can be commander, and to do any of these things the commander has to be in the base. This is problematic the way I play, where me being the commander often is far from the base and when in need often does not have any quick way of getting back there. I made a small mission myself some time ago where I locked zeus to the base location. So whenever I or my friends needed anything from the base I could just press Y and build (if we had resources) whatever we needed to complete our mission. This was a really nice feature that gave you the feeling of being backed up by HQ while being on a mission. I know you could "build" things before you go on a mission, but with scarce resources its not always easy to know what you are going to need before you are out there. 

I also know that building stuff is done from first person in liberation, so to find a way of achieving this I am going to suggest that maybe when building a fob, you also build a commander figure that would just remain idle in your base. This person you can remote control, so that as a commander you would have a option on your scroll wheel to become Fob Bravo commander while the actual you would just remain idle. Then you can build that helicopter and send it to pick up your friends instead of telling them that you are currently doing recon in the mountain of Altis and that they can either walk for 30 minutes or just respawn because you neglected your role as the commander !

**Comment by veteran29** [comment]
I think instead of adding remote controllable unit it would be better to add _global build menu_. Also this build menu could be blocked until you build some sort of _antenna_ building.

It would work like this:
1. Select _BUILD_ from action list
2. Select _FOB_ from list (custom dialog)
3. Unit is built at selected FOB

Possible problems:
- Where exactly unit should be spawned? Script possibly can spawn units in another unit etc. so it should check for free space. Another possibility is displaying a map and spawning unit on click location so player is responsible to select proper location.

**Comment by SondreBakken** [comment]
I agree with you.. my suggestion for HOW TO do it is mainly based on ease of implementations and avoiding problems like the one you mentioned. 

But I like your idea of being outside range. This suggestion is to simulate having backup by HQ, and remote controlling into the FOB commander can be viewed as "contacting commander for support" and therefor should only be possible when inside range of a friendly radio tower

**Comment by Mike2306** [comment]
This is a much needed feature in my opinion. I face the same problem and most of the time the commander just respawns to be in the base to send backup or pickup.

Thumbs up for this!

**Comment by Mike2306** [comment]
I have tried the following and it worked pretty well so far. No bugs seen yet.

1. Use Advanced AI command mod
2. place one AI soldier in the FOB and leave him there
3. Use Advanced AI command to remote control him
**4. You will be able to build**

**Comment by Wyqer** [comment]
Guess the same would work without mod by just using zeus remote control (if you play with unlocked zeus).

**Comment by glothos** [comment]
I also have this kind of limitation. I also play with a small group of friends and a pickup is something we always need. Sometimes i leave an AI as a driver and send him back to base as soon as we get to the next capture point and when we finish, I tell him to pick us up. But sometimes he manages to crash the vehicle and the commander have to respawn to build a vehicle and an AI. Sometimes you can face some problems with the squad management as well.  But i still recommend you to do that, its rather annoying to deal with the pick up when every friend of yours just want to have some pew pew.
