### ISSUE TITLE
Suggestion: Upgrade to Armed Huron

### ISSUE THREAD

**Issue by sirloinsandvich** [KillahPotatoes/KP-Liberation#373]
### Basic Information
**Mission version: 0.963a**
**Map used: Altis**

Suggestion: For Vanilla assets, have a way to permanently upgrade the starting Huron to the armed variant for a set resource cost. I think the unarmed variant is a great way to start, but being able to get the armed Huron by default would be great for later in a campaign.

**Comment by Wyqer** [comment]
Even as it seems to be a "small thing", this would need some more work as the "Spartan 01" has a special status in the mission as "unique vehicle".
The armed Huron can be build as helicopter through the build menu.
Also an "upgrade" ability would need to define them for all presets and upcoming presets.

The basic thought is that the "mobile respawn" vehicles (Medic Truck and unarmed Huron) aren't armed as they provide (in default settings) a mobile respawn and full mobile arsenal.
