### ISSUE TITLE
Build and Recycle Range doesn't match when changed

### ISSUE THREAD

**Issue by Havoc302** [KillahPotatoes/KP-Liberation#374]
### Basic Information
**Mission version:**
0.963

**Map used:**
Altis and Lythium

**Mods used:**
RHS
F-18

Advanced everything (towing, lifting, etc).

**Dedicated or local game:**
Dedicated

**Source of the mission file (URL):**
https://github.com/KillahPotatoes/KP-Liberation/releases

### Individual Things
**Did you edit anything within the mission files?**
Changed addaction order to raise push crate to top.
Added in init for mag repack, bon recruitment and fusions admin menu.

**If yes, what did you edit exactly?**
Read above.

### Short Issue Description
If you change the FOB range from 125 to larger (150m for example) you get the option to build outside the 125 range but the resources show up zero and you can't actually build, you need to start building within 125 then walk out past that range. You cannot recycle anything between 125 and 150 as it says there's no salvage station in range of the FOB.

### Expected Behaviour
Ability to build and recycle outside the 125m range.

### Steps to Reproduce the Issue
Change default range to over 125m, walk outside 125m and attempt to build or recycle.

### Screenshots, Serverlog or any other helpful Information
https://steamuserimages-a.akamaihd.net/ugc/2422250350100872901/4E83D02663F02DA4CDD52BCEB677C98EB650E25C/
https://steamuserimages-a.akamaihd.net/ugc/2422250350100873217/A164885D484AD24434E4D61796112BEB3F5A1D08/

**Comment by Wyqer** [comment]
Good catch and you're completely right.
There was a fixed number for exactly the check if there is a salvage depot or resources etc. near.
Very good issue description, because I was able to find the possible issue location and fix it, just by reading your report.
Excellent!

**Comment by Havoc302** [comment]
No worries man, glad I could help!
