### ISSUE TITLE
More resources.

### ISSUE THREAD

**Issue by DarkSideDK** [KillahPotatoes/KP-Liberation#378]
Hello.

I'm playing with two friends of mine on a dedicated server, and we're enjoying the map a lot (besides getting our asses handed to us severely, most of the time).

I find it very hard to keep up with losing units and vehicles, with only two places to generate resources for us. How do I increase the amount of resources we get? And how do I decrease the amount it takes for it to respawn? I couldn't find anything about this in the Liberation wiki.

Thank you so much in advance :)

**Comment by Wyqer** [comment]
https://github.com/KillahPotatoes/KP-Liberation/wiki/EN_ConfigFiles

Mission Parameters (Resource Multiplier)
https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/ui/mission_params.hpp#L99

Liberation Config File
https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/kp_liberation_config.sqf#L107

**Comment by DarkSideDK** [comment]
I could only find the "Resource Multiplier", I don't think I have the other lines of code anywhere.
I turned the multiplier to 50. What does that mean? That 50 crates will spawn every 30 minutes?

**Comment by Wyqer** [comment]
It's a multiplier. It speeds up the production by the factor (so it divides the production time by the value).
And you have the other lines.
Have a look at this article:
https://github.com/KillahPotatoes/KP-Liberation/wiki/EN_ImportantHints

**Comment by DarkSideDK** [comment]
Thank you so much for the replies! <3 

I will try and get it to work.
