### ISSUE TITLE
Unlockable mod-vehicles?

### ISSUE THREAD

**Issue by DarkSideDK** [KillahPotatoes/KP-Liberation#388]
Hello, just a quick question.

Is there a list for aircrafts and other mod-vehicles, that are compatible with the map? And can I add them on the fly? Like I mean, do I have to restart the entire map if I want to add new unlockable vehicles? Or can I just buy them immediately?

**Comment by Blakmane** [comment]
If by 'unlockable' you mean, locked to start and have to unlock them by taking a military base, then you will have to restart the map if you want that mechanic to function. If you just want to be able to buy mod vehicles, you don't need to restart the map. There's no 'compatible' list but basically anything should work - you'll have to add it to the appropriate preset list in the mod folder and define pricing etc. but if you look at the presets you should be able to figure this out pretty easily.
