### ISSUE TITLE
Win condition and end campaign

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#393]
Implementation of a check for the win condition X. (e.g. all capitals captured)
If the win condition returns true, display a debriefing screen, wipe the save and end the mission.

**Comment by RaulPro19** [comment]
It would be nice to let the players choose between wipe the game when the wind conditions are true or keep the save to clear the map.

**Comment by Wyqer** [comment]
In the end I'm thinking about a "what's needed to win" kind of parameter.
This won't be implemented in the first iteration of 0.97, of course. But later on I guess there won't be just "the win condition", there will be "one selected win condition from many"
Maybe something like
* All capitals
* All capitals + 66% of all sectors
* All capitals + 80% of all sectors
* All sectors
* etc.

**Comment by Dubjunk** [comment]
Maybe there should be an option or something like an debug, which can be used to slow the progress of the players.
I'm thinking about something like instant recaptures of x% (of the owned BLUFOR bases) near to some enemy bases.
