### ISSUE TITLE
deeper radio tower mechanics

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/KP-Liberation#394]
Thinking about some extra mechanics like hidden generators, which can deactivate the  radio tower functionality and slow / prevent enemy heavy / air vehicle reinforcements

**Comment by PhantomViper** [comment]
It would be great to see this and other elements of the mission expanded. Like intel and intel related missions. Radio towers could be tied into that. Would be great to see 0.97 released first though.
