### ISSUE TITLE
Bughunt for Sprint 1

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#404]
**What is this?**
This issue is used to collect all the bugs and problems that are found by the devs after a branch is merged or a sprint is finished. 

As we will release a working iteration of the new framework after every sprint, everyone is invited to help with testing the sprint results.
The only thing to remember is that you should only report bugs in this issue, which are caused by the contents of this sprint (which are listed below). So it is vital to look at the content description to see what was actually added. Only by reading this you know what we've really intended to implement and defined as done.
I guess you understand that reporting things which weren't even planned to be part of the sprint won't help in any way.

**Content of the sprint**

| Epic | Description |
| --- | --- |
| #379 | Basic CTI functionality |

| Task | Description | PR |
| --- | --- | --- |
| #380 | Creating a missionfile with prepared markers | no PR |
| #381 | First init module iteration | no PR |
| #382 | Function and UI fetching | no PR|
| #383 | Config file and mission parameters | no PR |
| #384 | Parameter save/load/use selected | #395 |
| #385 | Preset files conversion | no PR |
| #386 | Core module with basic and mostly everywhere needed functions | no PR |
| #387 | Handle respawn and mission intro | no PR |
| #390 | Spawn of start vehicles | #396 |
| #391 | FOB Box and placement | #411 |
| #392 | Sector activation and ownership change | #400 |
| #393 | Win condition and end campaign | #408 |

**Released sprint result**
https://github.com/KillahPotatoes/KP-Liberation/releases/tag/v0.97S1

**Bugs found so far**

| Related Task | Description | Reported by |
| --- | --- | --- |
| #387 | ~~Spawn issue, when intro is disabled: Sometimes no respawn dialog and camera running forever.~~<br>fixed in 669a8824b71b14e4153b5812f53a769d554ca508 | @veteran29 |
| #387 | ~~Closing respawn dialog via ESC let you run around at the starting position.~~<br>fixed in 92f18e29286b9f856f75fa3000d67cc50b1655ce | @veteran29 |
| #387 | ~~Intro sometimes breaks with error about cursor pos. Might be caused by alt-tabbing during it (using borderless window). See [log](https://github.com/KillahPotatoes/KP-Liberation/files/1998945/intro_error.txt)~~<br>fixed in https://github.com/KillahPotatoes/KP-Liberation/commit/669a8824b71b14e4153b5812f53a769d554ca508 | @veteran29 |
| #384 | ~~Default value for weather param is 3~~<br>fixed in https://github.com/KillahPotatoes/KP-Liberation/commit/10d3387ec2714a0e2a5eda7684861605e71196d3 | [BSO] ShadowFox |
| none | [NO bug] `KPLIB_fnc_core_spawnVehicle` can potentially get scheduled and this can cause bugs, we should consider wrapping it in `isNil {};` to prevent possibility of that | @veteran29 |

**Comment by Wyqer** [comment]
**Weather Param**
Default value set to 3 by an value array of [0,1,2].
Thanks to [BSO] ShadowFox from our Discord.
Ref: https://github.com/KillahPotatoes/KP-Liberation/blob/v0.97S1/Missionframework/KPLIB_params.hpp#L128

**Comment by PhantomViper** [comment]
Unsure if this is intended or not but with the S1 build there were no OPFOR spawning. No mods, didn't modify any mission files or parameters either.

Fresh game, flew to nearest locations and no enemies.

**Comment by Wyqer** [comment]
Please have a look at the content of the initial posting.

> Only by reading this you know what we've really intended to implement and defined as done.
