### ISSUE TITLE
Informant driven officer located failing to complete

### ISSUE THREAD

**Issue by mwpowellhtx** [KillahPotatoes/KP-Liberation#406]
Don't know if this is a server specific (i.e. script alteration) or core ``KP-Lib`` issue, per se. It appears like the officer is found, and even after eliminating him, there is still a counter running that indicated he got away. The mission area fails to clean up properly in either event afterwards, like perhaps the criteria for completion, whether pass or fail, are not satisfied.

**Comment by Wyqer** [comment]
Haven't experienced or heard of issues in this direction.
A serverlog with enabled civ info debug would be helpful.
Ref to "end hvt event":
https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/scripts/server/civinformant/tasks/civinfo_task.sqf#L48

**Comment by mwpowellhtx** [comment]
I don't have access to that, I'm just an end user in the equation. However, I'm taking a deeper dive and would like to startup a clan, and launch a KP Liberation server of my own. It wouldn't surprise me if it was some custom coding went awry, but who knows. We'll see how that goes and if I learn more will follow up.
