### ISSUE TITLE
What exactly is GRLIB_resources_multiplier

### ISSUE THREAD

**Issue by mwpowellhtx** [KillahPotatoes/KP-Liberation#407]
From code inspection, it looks like it potentially throttles not only found (floating) crates, i.e. at towns, factories, and the like, but also the rate at which crates are produced. But it doesn't stop there; it appears to also influence the number of units spawned in a given sector along a similar throttling. Any reason why that needs to be a connected number?

**Comment by Wyqer** [comment]
GRLIB_resources_multiplier affects only these aspects:
* [Spawned crates upon sector activation](https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/scripts/server/sector/manage_captureboxes.sqf#L9)
* [Production interval](https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/kp_liberation_config.sqf#L107)
* [Amount of soldiers which can be built by blufor side](https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/scripts/server/resources/recalculate_resources.sqf#L9)

**Comment by mwpowellhtx** [comment]
I'm considering separating the concerns a bit, but I've forked to pursue this question.

A bit off topic, when I build, what else do I need to do in order to package the mod for deployment? PBO the output folder? Do any other concerns go there in the built folders? i.e. hooking up additional mods, like TFAR, Advanced Sling Loading, Advanced Towing, Advanced Urban Rappeling, etc?

**Comment by Wyqer** [comment]
Liberation is no mod, it's just a mission. So you just need to pbo the missionfile.

**Comment by veteran29** [comment]
FYI
If you have nodejs you can build mission via "build.bat" (it runs gulp tasks that package mission variants defined in json configuration file. readme [here](https://github.com/KillahPotatoes/KP-Liberation/tree/master/_tools))

**Comment by mwpowellhtx** [comment]
Yep, I discovered that. Works quite well. Once built, I just identify that as the mission file/bundle?

**Comment by mwpowellhtx** [comment]
@veteran29 Thanks! I'll tune in to discord as well.
