### ISSUE TITLE
Removing of all fog effects

### ISSUE THREAD

**Issue by Mikkall** [KillahPotatoes/KP-Liberation#412]
KP_Liberation_Tanoa
DL'd from Github
Dedicated Server
No Editing

For 2 or 3 days now (I think since Friday), we've had a solid, hard fog going on.  It's pretty much unplayable (as we are fairly certain the AI can see right through it).

Don't know if this is a glitch, or we're simply hitting the server during heavy fog coincidentally.

**Comment by Wyqer** [comment]
Guess the second.
If you want to play always without fog again, just revert this commit:
https://github.com/KillahPotatoes/KP-Liberation/commit/21cfcc3bf1519f6f8c73fe5711c813c99792496b

**Comment by Mikkall** [comment]
Wow, thanks for the quick reply.  Just did a server reset (manually) and the fog is gone.  That said, I set the missions.param to reset every few (6hrs I think) hrs.  Don't know what's up with that.

**Comment by Wyqer** [comment]
In 0.97 there will be a weather module like in the old one. Additional it'll have some settings for the admin, of course.
