### ISSUE TITLE
Free Camera view for building

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#415]
We think about reworking the way you build in Liberation.
Instead of running around with the vehicle/building floating in front of you it should switch to a free roaming camera (like the zeus or spectator view). This allows you to "fly" around inside the FOB area to place down buildings and vehicles.
With this first step we'll evaluate the possibilities and how we could implement this. It won't implement the complete building system, it's just for the "how you build" aspect.
But this will indeed be settled in the "build module", which will be created during the implementation.

**Comment by mwpowellhtx** [comment]
Will be following up in context of my own initiative to rekindle this effort. However, curious for thoughts and feedback concerning a couple of topics:

* Alignment with compass headings is HUGE. For those of us that are engineer oriented anyway.
* Ability to see the objects as they rotate freely, in ghost or "real" or whatever form.
* Ability to raise, lower, etc.

Overall, I like the innovation, but for the aforementioned opportunities.
