### ISSUE TITLE
Sectors respawn OPFOR at full strength if all players are killed.

### ISSUE THREAD

**Issue by benleedy** [KillahPotatoes/KP-Liberation#431]
### Basic Information
**Mission version:** 0.963a
**Map used:** Malden
**Mods used:** MCC Sandbox 4, ALiVE, Enhanced Movement, No Weapon Sway, 3CB BAF Vehicles
**Dedicated or local game:** Local
**Source of the mission file (URL):** Steam Workshop

### Individual Things
**Did you edit anything within the mission files?**
No.

### Short Issue Description
When attempting to liberate a sector if all players are killed all OPFOR respawn at full strength within seconds.  After being killed I used MCC to teleport back into the sector and within a second of the teleport they respawned.  Playing with a friend we also found that if we were both killed when we respawned outside of the sector and walked back OPFOR was at full strength.  This has been observed at multiple sectors.  It seems like the entire sector is resetting, replacing remaining forces with fresh troops.

### Expected Behaviour
Sector reinforcements should be on a timer of some kind, regardless of player presence.  In addition, reinforcements arriving by vehicle (troop carrier), or parachute would be ideal rather than them simply spawning into the middle of the sector.

### Steps to Reproduce the Issue
Begin attacking a sector, then die.  When you return the sector will be at full strength.

### Screenshots, Serverlog or any other helpful Information
N/A

**Comment by Wyqer** [comment]
This is the intended behaviour since 0.963, so no bug.
In 0.97 you can expect changes on this aspect.

**Comment by benleedy** [comment]
Understood.  Is there a setting that can prevent or delay this so we aren't starting from scratch every time we die?  How is it changing, if you care to shre?

Thank for responding so quickly, this is my favorite way to play ArmA and I'm happy to see it's still being actively developed.

**Comment by Wyqer** [comment]
You can raise this number:
https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/scripts/server/sector/manage_one_sector.sqf#L22
1 Ticket equals ~5seconds

**Comment by benleedy** [comment]
Okay, so does that setting of 12 mean that after ~60 seconds it refreshes the area if no players are present?

**Comment by Wyqer** [comment]
Yes, of course. 12 * 5 = 60.
