### ISSUE TITLE
Aircraft counters between FOBs not working

### ISSUE THREAD

**Issue by Lazza101** [KillahPotatoes/KP-Liberation#433]
### Basic Information
**Mission version: 0.963a
**Map used: Altis
**Mods used: Enhanced Movement, C2 Command & Control, Bloodlust, CBA A3, Blastcore (standalone), Project SFX, server-side smoke for blastcore.
**Dedicated or local game: Dedicated.

### Individual Things
Edited the FOB building, changed it from Land_Cargo_HQ to Land_Cargo_Tower. Also removed nightstalker and tws from default blacklist.

### Short Issue Description
FOB helo and fixed-wing aircraft count appears to be global instead of different for each FOB. All aircraft built by a player during a session are destroyed (they literally explode) when that player disconnects from the server.

### Expected Behaviour
FOB aircraft counters to behave as normal and aircraft not to explode.

### Steps to Reproduce the Issue
Build a FOB and give it a radio tower and a hangar/helipad. Build another FOB somewhere else and it will instantly have the same aircraft counters (e.g. 0/1) as the first FOB. You cannot build aircraft there until a radio tower and hangar/helipad are built, however now at both FOBs the counter will read 0/2, and any aircraft you build will explode when you disconnect.

**Comment by Wyqer** [comment]
> FOB helo and fixed-wing aircraft count appears to be global instead of different for each FOB.

Which is right and intended.

> All aircraft built by a player during a session are destroyed (they literally explode) when that player disconnects from the server.

Sounds weird, haven't experienced something like this.

**Comment by Lazza101** [comment]
Oh, right I wasn't aware that the counters were supposed to behave that way. I always thought that the aircraft exploding were related to this, but now I'm back to square one.
