### ISSUE TITLE
Add Better Wiki

### ISSUE THREAD

**Issue by Phantom-LF** [KillahPotatoes/KP-Liberation#438]
Could you add a more detailed wiki? I was trying to see how to get aircraft, thought it was the flight control but resources were tight so I didn’t want to risk buying the wrong thing. After digging around I found something in some old changelogs that confirmed it was the flight control. Detailed descriptions on each item on the wiki or in-game would be nice, but probably put at the back of development. Perhaps a community wiki where we could add stuff to help players?

**Comment by Wyqer** [comment]
After the refactoring, the wiki will be updated with the new mechanics etc.
Currently it's no priority.
Until the 0.97 is finished, try this article:
https://github.com/KillahPotatoes/KP-Liberation/wiki/EN_FAQ#buildings-and-their-purposes
