### ISSUE TITLE
Certain Vehicles Can’t be Spawned

### ISSUE THREAD

**Issue by Phantom-LF** [KillahPotatoes/KP-Liberation#439]
### Basic Information
**Mission version:**
0.963a
**Map used:**
Altis
**Mods used:**
Ace
A-10
F16
F18
F15
RHS
**Dedicated or local game:**
Local
**Source of the mission file (URL):**

### Individual Things
**Did you edit anything within the mission files?**
No

**If yes, what did you edit exactly?**

### Short Issue Description
Sooo for RHS I can buy certain 6 wheeled NATO trucks but not the 8 wheeled ones that could carry more. For the planes I can purshase the F15 and F18 but not the F16. I also can only purchase the A10A and not the A10C. 
### Expected Behaviour
I definitely expected to buy those trucks, and seeing the F18 and F15 work I expected to be able to buy the F16.

### Steps to Reproduce the Issue
Try and buy something that can’t be bought. 

### Screenshots, Serverlog or any other helpful Information
Link to the actual modlist Im using: https://steamcommunity.com/sharedfiles/filedetails/?id=1425586413

**Comment by Phantom-LF** [comment]
I don’t really know what you do to detect modded vehicles, if it’s a automatic script that detrcts new vehicles and puts a price on them that it thinks is balanced or if you have to go in and recognize and put a price on every vehicle for each mod you support.

**Comment by Wyqer** [comment]
You have to adjust your preset:
https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/presets/blufor/custom.sqf

Wiki:
https://github.com/KillahPotatoes/KP-Liberation/wiki/EN_ConfigFiles#presetsbluforopforresistancecivilianscustomsqf
