### ISSUE TITLE
Building Camera pt.2

### ISSUE THREAD

**Issue by veteran29** [KillahPotatoes/KP-Liberation#443]
Free camera view needs to be finished.

During the implementation flaws listed in initial PR (#441) have to be fixed. Additionality new features like item rotation should be added.

TODO:
- Fix camera zoom when scrolling the items list
- Item rotation
- Item collision detection
- Add stub methods for resource integration
- Limit camera area to FOB area
- Allow to build only in FOB area
- Close camera when player unit dies
- "Ghost" of an item that will be built
- Info about current FOB

**Comment by Wyqer** [comment]
We could also think about this:
* Raise/Lower Items
Maybe just specific ones like HMGs, H-Barriers, Sandbags etc. So things which are sensible to be built on higher positions.
* Visual building range borders
Maybe using these green balls (which are now show the borders of the object in the 0.963 framework) to visualize the build (and therefore save) area. Could be a better usability then just a "outside of area, can't build" hint when the "ghost" is moved outside of the area.
* For item rotation: free mode and "grid mode" which then changes the orientation by 10 (or 5) degree steps at fixed values (0, 10, 20, 30, etc.).
* Removal of units/vehicles from the build menu
I guess we'll implement a different build/order system and dialog for units and vehicles.
