### ISSUE TITLE
No Units Spawning

### ISSUE THREAD

**Issue by hakasapl** [KillahPotatoes/KP-Liberation#446]
### Basic Information
**Mission version: 0.963a**

**Map used: Pulau (This is a custom mission using your DevKit)**

**Mods used: 
CBA_A3
CUP Weapons
CUP Units
CUP Weapons
Pulau
RHS AFRF
RHS USAF
RHS GREF
Specialist Military Arms
USSOC_Lite_mas, task_force_radio**

**Dedicated or local game: Dedicated (Tested on local)**
**Source of the mission file (URL): https://steamcommunity.com/sharedfiles/filedetails/?id=1433893511**

### Individual Things
**Did you edit anything within the mission files?**
Yes

**If yes, what did you edit exactly?**
Created an entire map for pulau following the instructions in the devkit wiki. I edited kp_liberation_config.sqf to change BLUFOR to rhs usaf wdl, OPFOR to rhs afrf, and Resistance to RHS gref. I changed some of the presets for blufor rhs usaf wdl as well. I also changed some of the default mission settings.

### Short Issue Description
No enemy units spawn at sectors. When I get there the capture bar turns completely blue because there is no one there.

### Expected Behaviour
Enemy units to spawn.

### Steps to Reproduce the Issue
I will attach my mission pbo. You can use that to see the problem.

### Screenshots, Serverlog or any other helpful Information
I read on the wiki that this could be due to the mods not being installed, but I do have all the required mods. I tried this mission with no mission files edited (just the mission.sqm that I made with the mission framework unedited) and the same issue was present either way.

**Comment by Wyqer** [comment]
Attach a full serverlog from a session where you captured a sector without enemy spawn.

**Comment by hakasapl** [comment]
I never captured a sector. The bar would just turn blue, but the text field for the sector name would still be red, and it would stay like that. There were no enemies to kill.

**Comment by Wyqer** [comment]
That log would be sufficient.

**Comment by hakasapl** [comment]
Okay do you know where I would find a log on a local server? (I'm doing my testing on a local server)

**Comment by Wyqer** [comment]
`C:\Users\<yourUserName>\AppData\Local\Arma 3`

**Comment by hakasapl** [comment]
[Arma3_x64_2018-07-07_01-52-07.zip](https://github.com/KillahPotatoes/KP-Liberation/files/2172488/Arma3_x64_2018-07-07_01-52-07.zip)
Just got this log:
1. Spawned in on the LHD (in the custom mission.sqm)
2. Flew to the military base in the SE island and landed.
3. got out (bar was full blue, no enemies, and the sector was not captured)

**Comment by Wyqer** [comment]
Looks fine on the first look.
Do this once and test it again:
Set all the presets to the unedited custom sqf (0 for each preset) which will use only vanilla assets.
Check again, if there are no enemies.

**Comment by hakasapl** [comment]
I've done that already, and unfortunately it was the same issue. Could this be because of the specific map?

**Comment by Wyqer** [comment]
Could be, that you've made a mistake in the missionfile itself, of course.
I would recommend you join the discord and share your missionfile (sqm is enough) there. Someone from the hundeds of players there might have the terrain installed and can check it. Also it could be a place to advertise your derivative.
Discord link is in the readme or the main page of GitHub.

**Comment by hakasapl** [comment]
I'll give that a shot, thanks for the help!
