### ISSUE TITLE
Custom Variables for Vehicles

### ISSUE THREAD

**Issue by Marcel40625** [KillahPotatoes/KP-Liberation#450]
I have set "CUP_B_RG31E_M2_USMC" for my mobile spawn, the only problem its not supporting TFAR radios.

But its possible to set the init so that it has a radio:

this setVariable ["tf_hasRadio",true ,true]; 
this setVariable ["tf_side",west , true]; 
this setVariable ["tf_range", 50000, true]

but how do i set it up in the scripts that when i build a vehicle it gets the init?

im not that advanced in arma scripting

thx for any help

**Comment by Wyqer** [comment]
Do it when save is loaded:
https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/scripts/server/game/save_manager.sqf#L264

Do it upon building:
https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/scripts/client/build/do_build.sqf#L334

Adapt from the existing events for specific classnames

**Comment by Marcel40625** [comment]
great thank you ... that worked ... but it seems that there is a type of cleanup ... at first when i jump in i have radio after second try its gone ... any idea?

**Comment by Wyqer** [comment]
There is no kind of cleanup which removes variables from objects.
Post the lines you've added to both of the files.
And what's exactly the "second try"?

**Comment by Marcel40625** [comment]
mhm pretty odd, after another restart now it seems to stay ... sorry

save_manager:
``if (_nextclass == CUP_B_RG31E_M2_USMC) then {
				_nextbuilding setVariable ["tf_hasRadio",true,true]; 
				_nextbuilding setVariable ["tf_side",west,true]; 
				_nextbuilding setVariable ["tf_range",50000,true];
			};

**Comment by Wyqer** [comment]
Yeah, edits are good. Maybe TFAR had some kind of "reinitialization" or lag or anything and because of that it didn't worked that one time.

**Comment by Marcel40625** [comment]
okay its still not fixed, it seems that the radio disappears from the vehicle when you get far away. we had 3 cars in our FOB, took 2 of it, to fight, after ~2 hrs of fighting we came back to the FOB and the radio of the third car was gone. ...

**Comment by Wyqer** [comment]
You should head to the support of TFAR, as Liberation don't has any script which deletes variables on objects. And yes, Liberation uses own variables on objects which persist as they should be.

**Comment by Marcel40625** [comment]
okay thanks for the input :) great work with Liberation
