### ISSUE TITLE
[question] less armored enemy & more infantry

### ISSUE THREAD

**Issue by Marcel40625** [KillahPotatoes/KP-Liberation#451]
im playing Liberation with a group of max. 10 players, and the Tank presense is way to much in my opinion, is there a quick and dirty way to reduce the amount of tanks and increase infantry ?

**Comment by Eogos** [comment]
yea, go into the presets and remove some of the heavy armor from the spawn list and/or just keep your alert level low so you only see lighter vehicles

**Comment by Marcel40625** [comment]
thx :)
