### ISSUE TITLE
Planned support for new Jets DLC addons

### ISSUE THREAD

**Issue by Lazza101** [KillahPotatoes/KP-Liberation#452]
Are there plans to implement the new stationary radar and SAM sites mentioned in the 26/06 sitrep? (https://dev.arma3.com/post/oprep-jets-dlc-bonus-content) They would be extremely useful additions to be able to build at FOBs to protect the airspace around them, and for CSAT to have as part of their FOBs, scattered around the map and/or as another target to go after similar to the FOB Hunt secondary mission.

**Comment by Wyqer** [comment]
These things will surely be added in the next version. The airspace will get some changes in general, so it's more dangerous to get troops behind enemy lines with helicopters etc.
