### ISSUE TITLE
released mission ver 0.97 seems not playable

### ISSUE THREAD

**Issue by DracheTek** [KillahPotatoes/KP-Liberation#454]
## Question: 
 
The mission ver 0.97 sprint 3 seems not playable when I downloaded and tested it. All game specific actions are plain white instead of colored in 0.96x, and FOB container disappeared when I choose "Deploy FOB". KillahPotatoes flag on the carrier is black, which possibly means that the texture is missing. 

The size of ver 0.97 is only about half of 0.96x, so I am wondering if it did not include some important files(?). Please confirm.

**Comment by Eogos** [comment]
the 0.97 sprints are not full releases, they are test pre-releases meant for bug hunting. 0.963A is the current release version.

**Comment by Wyqer** [comment]
From the "read this, if you download this" link from the release page
>This releases (which are also marked as Pre-release) aren't meant to be played as replacement for the current framework. It is for testing purpose or a kind of first look at features/changes which will be part of the 0.97 release in some months.

If you like, you can of course test the things which are done during the current refactoring and state things you notice in the review isse #445 . But this make it necessary to really follow the stated instructions, it'll give you all the needed information.

If you just want to play Liberation, you should stick to the latest release and ignore all pre-releases.
