### ISSUE TITLE
Enemy POW not following me nor do they stop surrendering

### ISSUE THREAD

**Issue by DracheTek** [KillahPotatoes/KP-Liberation#455]
### Basic Information

**Mission version:**
0.963a
**Map used:**
Altis
**Mods used:**
ACE
CBA_A3
MCC4
ShackTac UI
Enhanced Movement
Advanced Rappeling/Towing/Urban Rappeling
RHSUSAF/RHSAFRF/Corresponding ACE compatibility files

**Dedicated or local game:**
dedicated
**Source of the mission file (URL):**

Official Steam page
### Individual Things
**Did you edit anything within the mission files?**
No

**If yes, what did you edit exactly?**
No

### Short Issue Description
When activate "capture" action on a surrendering POW, he does not stop surrendering nor does he follow me. It have not happened on my local hosted game.

### Expected Behaviour

Prisoners are supposed to follow me after "capture" action.

### Steps to Reproduce the Issue

Host the game in dedicated server, and join the game.
Win a battle by adding some friendly force thus create some prisoners. 
Try activate capture action on prisoner and see what happens.

### Screenshots, Serverlog or any other helpful Information
I have no access to Dropbox and other online drive service. Please tell me an alternative so that I can send server log.

**Comment by Wyqer** [comment]
If you use ACE, you should ziptie the POW, use the "capture" action and escort him to your FOB.
