### ISSUE TITLE
Replace USS Freedom with USS Liberty

### ISSUE THREAD

**Issue by Wyqer** [KillahPotatoes/KP-Liberation#462]
The USS Liberty would provide enough space for:
* 1 Start Helicopter (Potato 01)
* 2 Boats
* Resources
* FOB Box
* Medic installment

Personally I guess using the Liberty would also eliminate the question about "Why are there no jets on the carrier?" and the Liberty would be a more immersive vessel to start from (we still have to provide something for maps without water, of course).

Weapon systems on the Liberty could be controlled or "asked for" via a kind of "commander menu" which should be implemented later during the development. Or just leave it empty, which I wouldn't prefer. But giving players access to the weapon systems directly could lead to a too big advantage.
Guess we'll see how exactly we do this, as soon as we hit that stage of development. First replacing the Freedom and provide all needed assets for a campaign start would be part of this task.

Sub-Tasks:
- [x] Remove USS Freedom and place USS Liberty
- [x] Adjust the position of all markers/grasscutters
- [x] Provide the medic container building (guess in the back of the hangar)
- [x] Replace flag with KP flag and set Hull Number to 758
- [x] If possible, make the available boats at the sides spawnable inside the racks. Otherwise preplace them there
- [x] Place down weapon systems, but deactivate them for now
- [x] Adjust start vehicle spawn scripts accordingly
- [x] ~~Change "Intro Cinematic Label", maybe two strings for Liberty and Chimera with a check if the spawn is on water~~ *Postponed to Sprint 6 due to some issues with the intro cinematic in general*
- [x] ~~Eventually prepare a kind of "Liberty/Chimera dialog" already for later functionalities~~ *Will be moved to a "Startbase Dialog" later.*
- [x] ~~Find a nice way to provide a Little Bird spawned in the hangar and make it able to be "moved to the aft deck" if the Potato 01 is gone from there. Or postpone this implementation for the dialog functionalities~~ *This would also be part of the mentioned dialog for the startbase.*

**Comment by Wyqer** [comment]
Added some first Sub-Tasks

**Comment by EJEESMartin** [comment]
About "Weapon systems on the Liberty" availability for the player. Maybe have access to reload those weapons and use them when you reached 1000 points in ammo and 1000 points in fuel or something like that. For sure you guys will figure it out later xD.

**Comment by Wyqer** [comment]
The general thought is to have a "pay X ammo to rearm with Y rockets/artillery shells" or something similar.

**Comment by EJEESMartin** [comment]
Sound good. That's a good choice guys.

**Comment by Dubjunk** [comment]
It would be a nice feature for the defense weapons too, for example you activate the Gatling or SAM for x resources. On the other hand there could be something like an event where enemy aircraft attacks the destroyer.
