### ISSUE TITLE
Dedicated Server Installation Issues

### ISSUE THREAD

**Issue by Nynex711** [KillahPotatoes/KP-Liberation#474]
So I was looking for some guidance on how to install the framework. I've set up the mission and I get one error when trying to select a role on the server.
"res/kpflag.jpg not found"

I've been messing around trying to figure out where I should place the framework but nothing I have tried worked and I couldn't find any resources online. I'm going to apologize now because I'm almost certain this isn't the right place to ask this question.

Thanks in advance, any and all help is appreciated.

**Comment by veteran29** [comment]
Please download the mission from releases tab https://github.com/KillahPotatoes/KP-Liberation/releases/tag/v0.963a-Hotfix3

If you need further assistance please go to our Discord server.
