### ISSUE TITLE
Suggestion: force multipliers for sector defenders / enemy in general

### ISSUE THREAD

**Issue by Lordeath19** [KillahPotatoes/KP-Liberation#475]
In combat there are force multipliers; APCs, Tanks, Gunboats, Gunships, etc'.

My suggestion is adding the force multipliers to all units inside said vehicle and blending it in the calculation for sector capturing.

For example:

10 **infantry**
vs
2 **tanks** manned by 4 men, 4 **APCs** containing  **infantry** + 8 crew members, 1 **gunship** with 2 crew members and 10 **infantry** men

lets say **tanks** are a force multiplier of 10, **APCs** are a force multipliers of 5 and a **gunships** are a force multiplier of 15

2(tanks) * 10 = 20
20 + 4(APCs) * 5 = 40
40 + 1(gunships) * 15 = 55
55 + 10(infantry outside vehicles) = 65

65 total **force** from the capturing team and
10 total **force** from the defending team

(65/(10 + 65)) * 100 = 86% force advantage for attackers

**note that infantry inside vehicles that aren't able to fight are not considered a force, until they get out of the vehicle they won't be a part of the calculation**

this is only an example and the number of the force multiplier can change or even be a parameter in the mission

**Comment by Wyqer** [comment]
The template you see after selecting an issue type isn’t a training for `ctrl+a` and `del` by the way.

We’ll keep this in the suggestions category and have a closer look as soon as we’re start implementing the enemy in 0.97.

Also have a look at #329.
