### ISSUE TITLE
Some suggestions and possible features

### ISSUE THREAD

**Issue by enemperic** [KillahPotatoes/KP-Liberation#476]
## Suggestion/Feature request

Hi. This is my wishlist for the future of Liberation. We play this mode in my clan everyday and make our own heavy modded missions but we want go further so here are mu ideas.

1.- Resource depot class.
       It would be great to be able to select which kind of resource you want in a place when editing to make more inmersive and real missions. For example "I want Fuel in a refinery",  "I want ammo in a military base" or "I want supply in a factory".

2.- Secondary missions
       We need more secondary missions, for example:
                     a) Take resources to a town = better civil reputation
                     b) Medevac a civil = better civil reputation
                     c) Patrol and deactivate IEDS = better civil reputation
                     d) More Inteligence missions = more intelligence points
                     e) sabotage missions (maybe underwater?)

3.- Naval warfare
         I saw there is a suggestion about it in other issue, but It's a great idea

4.- Change some of the KP default Fob Buildings and add another by deffault.
                                Salvage depots from this ugly garage to the repair center fron "TANKS"
                                Air vehicles building (dome radar) to a mobile radar or antenna
                                Build wooden piers
5.- Don't know if possible or if it's mod dependant but the cargo space for vehicles is a nightmare (you can put more crates in a chinook than in a blackfish or RHS-C130. Can be edited in anyway?

6.- Virtual garage.
      It would be awesome to be able to change the vehicles apperance (texture and variants) without been able to spawn a new (and resource free) vehicle. So you can "paint " the vehicle you purchased. I know it can be done but don't know how (I saw it in EXILE).

7.- Air raid sound
     Play an alarm sound when your FOB is under attack.

8.- Farps and outposts
      Posibility to create a kind of "light FOB" with limited construction assets. (no IA, no vehicles, no resources, no buildings. No respawn. Only a place you can build some sand barriers, paint an heliport put a windcone an deploy some huron containers that remains there after server restarts.

And That's all for today.
Thank you for a wonderful and hard work.

Ric

**Comment by Wyqer** [comment]
1. Guess I'll add a possibility for this in the next version. Like adding a variable to the marker to specify it. Something "simple and possible in the eden editor".

2. This is already on the roadmap

3. See 2.

4. Beside of the fact, that you can exchange everything in the config files very easily, you can expect some adjustments there.

5. Look at the transport configs in the config file.
https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/kp_liberation_config.sqf#L296

6. A "switch loadouts and assets/camo of vehicles" will be part of 0.97.

7. Nothing with priority

8. A similar thing is on the roadmap. Not in detail, but as a basic thought
