### ISSUE TITLE
Make military bases act as firebases

### ISSUE THREAD

**Issue by Freddo3000** [KillahPotatoes/KP-Liberation#478]
### Is your feature request related to a problem? Please describe:
It is not related to a problem.

### Describe the solution you'd like:
Add a mortar to military bases that will provide fire support to sectors within a certain radius.
This mortar may be replaced by a howitzer or similar as readiness progresses.
Possibly make it so recon units/snipers spawn within sectors close to military bases that direct the fire support.

### Additional context:
Who doesn't love getting shelled?

**Comment by Wyqer** [comment]
Possibility of enemy artillery will be something which will be implemented before the full release.
