### ISSUE TITLE
Problem Rcon mission 

### ISSUE THREAD

**Issue by diaverso** [KillahPotatoes/KP-Liberation#484]
Hi, I have the mission of Al Rayak.
When you put the mission, with the Rcon system,It gives an error when trying to connect users with the batteleye and ejects them from the server.

Why could this error be?

Thanks for the attention

**Comment by Eogos** [comment]
The problem is Battleye is a piece of trash, try turning it off. My group hasn't used it for years now due to it's fuckery.

**Comment by Wyqer** [comment]
As this isn't connected to the mission at all, I recommend you head over to the support of Battleye, the RCON Tool you use or your server provider.
