### ISSUE TITLE
Indestructible Objects

### ISSUE THREAD

**Issue by TheKukyCZ** [KillahPotatoes/KP-Liberation#485]
Hi, once we were talkin about that, but now it's closed and still not working. I need indestructible what I built, for example lights, fences etc.

I tried to add this to do_build.sqf

`case "my_desired_building_classname": {[_vehicle, false] remoteExec ["allowDamage"];};`

and this to save_manager.sqf

```
if (_nextclass == "my_desired_building_classname") then {
    [_nextbuilding, false] remoteExec ["allowDamage", 0, true];
};

```

I also tried this:

do_build.sqf:
`case "Land_BarGate_F": {_vehicle addEventHandler ["HandleDamage", {0}];` //somewhere after line 326

and this in the savemanager.sqf:
`if (_nextclass == "Land_BarGate_F") then { _nextbuilding allowDamage false;};` // after line 231

Nothing works. Thanks

My files example:
https://pastebin.com/cZykUdMe

**Comment by TheKukyCZ** [comment]
I have this: 
```
case "Land_Razorwire_F": {[_vehicle, false] remoteExec ["enableSimulationGlobal", 2]};

if (_nextclass == "Land_Razorwire_F") then {
				_nextbuilding enableSimulationGlobal false;
			};
```

but if civ or me doesn't matter, hit that by car, it will be destroyed.
okay, next time I will use Discord, but I dont know who and where I can ask.

**Comment by Wyqer** [comment]
As you're now in the discord, this is closed now.
