### ISSUE TITLE
Some items won't be saved and can't be recycled

### ISSUE THREAD

**Issue by d-man9000** [KillahPotatoes/KP-Liberation#487]
## Bug report
Sorry about the empty bug report. My browser refreshed before I hit submit, and I guess it wiped out everything I typed.

### Basic Information

**Mission version:**
.963a
**Map used:**
Altis
**Mods used:**
@Enhanced_Movement 
@POOK_Camonets 
@VSM_All-In-One_Collection 
@NIArms_MP5_SMGs 
@NIArms_Minimi_LMGs 
@NIArms_AWM_Rifles 
@NIArms_AUG_Rifles 
@Ares_Mod_-_Achilles_Expansion 
@RHSUSAF 
@RHSGREF 
@RHSAFRF 
@NIArms_P226_Pistols 
@NIArms_Core 
@FIR_AWS(AirWeaponSystem) 
@FA-18_Super_Hornet 
@F-22_Raptor 
@F-16_Fighting_Falcon 
@F-15_Eagle 
@CUP_Weapons 
@CUP_Vehicles 
@CUP_Units 
@CJTF_No_Helmet_Req_IR_Strobe 
@AV-8B_Harrier_2 
@Advanced_Urban_Rappelling 
@Advanced_Towing 
@Advanced_Rappelling 
@A-10_Warthog 
@CBA_A3 
@TRYK_[TRYK's_Multi-play_Uniforms] 
@NIArms_M14_Rifles 
**Dedicated or local game:**
Dedicated
**Source of the mission file (URL):**
Github

### Individual Things
We've changed custom.sqf for both bluefor and redfor, by using RHS units and additional CUP units

### Short Issue Description
Some objects that are purchased cannot be recycled, and do not save. Most items work fine. It would make sense if I messed something up from the CUP side, but other CUP units work. Additionally, some vanilla objects aren't working.

### Expected Behaviour
Bought objects/units/vehicles should save/be able to be recycled while still in the buy zone

### Steps to Reproduce the Issue
Buy CUP MH60L-DAP or vanilla radar unit from the bonus jets dlc. If the server restarts, they are not saved, and we are not able to recycle them

Additional units not working are the new BIS AA turrets. The CWS and SHORAD launchers.

### Screenshots, Serverlog or any other helpful Information

[arma3server_x64_2018-09-03_17-49-23.txt](https://github.com/KillahPotatoes/KP-Liberation/files/2353237/arma3server_x64_2018-09-03_17-49-23.txt)
![20180904230450_1](https://user-images.githubusercontent.com/42988636/45101070-b3387600-b0f8-11e8-8c2b-ba022131ce92.jpg)
![20180904230454_1](https://user-images.githubusercontent.com/42988636/45101071-b3387600-b0f8-11e8-8905-9f7a6c1583ca.jpg)
![20180904230500_1](https://user-images.githubusercontent.com/42988636/45101072-b3387600-b0f8-11e8-97d1-6f6fe5dea52c.jpg)

**Comment by Wyqer** [comment]
Your serverlog says you play 0.963 and not the latest version which is 0.963a.
Consider to update to the latest one, as it also contains tweaks to the recycling.
After updating have a look if your issue persists. If yes, enable the debug outputs in the mission parameters and attach a new log.

**Comment by d-man9000** [comment]
Cool, I just finished updating it. I'll try to get one of my players to test it out. Thanks for the quick response, and sorry again about the accidental empty post!

**Comment by d-man9000** [comment]
Just had a player test, he's still running into issues with some items(radar at least)

[arma3server_x64_2018-09-05_12-19-19.txt](https://github.com/KillahPotatoes/KP-Liberation/files/2353818/arma3server_x64_2018-09-05_12-19-19.txt)

**Comment by Wyqer** [comment]
No, everywhere below that header all defaults from 0 (disabled) to 1 (enabled). The header is empty.

Personally I can't reproduce the issue reliable in some small tests. If there was a vehicle which couldn't directly be recycled, leaving the FOB area for one minute and come back always brought me the needed action.

**Comment by d-man9000** [comment]
FIR is Firewill's stuff. Maybe one of his jets or the weapon systems pack.

**Comment by d-man9000** [comment]
So the FIR Pilot pack never loads on my server. I figured out how to fix that. But it has me wondering, maybe part of CUP vehicles isn't being loaded, which could explain the helicopter not saving or being recyclable. The radar and turrets from the Jets Encore DLC, though, I'm not sure what's up with that.

As far as I can tell, the Jets DLC piece loads, based off of the logs. I suppose I could run a listen server on my box with the same files, and see if I'm still having the error. It's probably something funky with my dedicated box.
