### ISSUE TITLE
add this to your wiki (command lines to to change ressources values)

### ISSUE THREAD

**Issue by Waloumi** [KillahPotatoes/KP-Liberation#510]
to change the value of ressources while in the game by using the debug console as host or admin

resources_infantry = value;
resources_ammo = value;
resources_fuel = value;

i had to dig a long time to find this and this should be quite an obvious thing to know!

**Comment by Wyqer** [comment]
Deprecated since about 1,5 years. Won’t be added.

**Comment by veteran29** [comment]
If anything it could be added to GREUH wiki:
http://greuh-liberation.wikia.com/wiki/GREUH_Liberation_Wikia

KP Liberation != GREUH Liberation
