### ISSUE TITLE
In-vehicle sound volume feature problem

### ISSUE THREAD

**Issue by Kornish** [KillahPotatoes/KP-Liberation#518]
### Is your feature request related to a problem? Please describe:
Hi. There is a problem with In-vehicle sound volume option doesn't work when I disable these options
_**GREUH_allow_viewdistance = false;
GREUH_allow_worldquality = false;**_
in 
**GREUH_config.sqf**.
In-vehicle sound volume option looks like this is linked to view distance option which I can't disable it separately (in-vehicle sound volume option separately from view distance options)

### Describe the solution you'd like:
This feature is so useful when flying loud planes and helis.
Can you make that volume feature always on whenever I disable view distance options or not, or to make it more professional, create new parameter in 
**GREUH_config.sqf** 
for example named; 
_**GREUH_allow_vehvolume = true;**_ 
so it will be easy to customize separately from view distance is on or off.
I will be grateful for this new option, or If you can tell me how to turn it always on.
Thanks
### Additional context:

![arma 3 screenshot 2018 11 04 - 12 23 27 87](https://user-images.githubusercontent.com/39022963/47964379-167b5180-e031-11e8-84ff-aa33ba2264e6.png)

**Comment by Wyqer** [comment]
The GREUH interface isn't used in the upcoming versions and it's just a deprecated feature in the legacy version of the framework.
With 0.97 the KP Player Menu is used.
https://github.com/KillahPotatoes/KP-PLM

**Comment by Kornish** [comment]
Will in-vehicle sound volume feature be switchable on and off separately from view distance being on or off?
It would be great to make config file for separate disable or enable all each features in future KP Player menu.

**Comment by Wyqer** [comment]
You should at least follow the link and read the provided information.
Everything in the menu is client side and provide "player likings" settings, which won't hold any config file to disable specific features for players.
