### ISSUE TITLE
UAVs spawn without AI

### ISSUE THREAD

**Issue by JoramD0** [KillahPotatoes/KP-Liberation#545]
## Bug report
**Mission version:**
v0.97S8
**Map used:**
Altis
**Mods used:**
CBA_A3
KP_Ranks
**Dedicated or local game:**
Dedicated
**Source of the mission file (URL):**
Official release on KP Liberation Dev Testserver
### Individual Things
**Did you edit anything within the mission files?**
No

### Short Issue Description
UAV's you build via the new buildsystem spawn without AI in it (making it unable to fly).

### Expected Behaviour

It should spawn with AI. Can be easily fixed with [createVehicleCrew](https://community.bistudio.com/wiki/createVehicleCrew)

### Steps to Reproduce the Issue

Place a UAV with the new build system and try to fly it.

### Screenshots, Serverlog or any other helpful Information
Not needed

**Comment by veteran29** [comment]
Thank you for the report, the issue will be fixed in next preview release.

For the future report preview releated issues in their respective sprint summary/dev-blog issue.
(https://github.com/KillahPotatoes/KP-Liberation/issues/544 for S8)

**Comment by JoramD0** [comment]
Ah I did not realize that, will do next time.
