### ISSUE TITLE
FOB Spawn Limitations

### ISSUE THREAD

**Issue by Phantom-LF** [KillahPotatoes/KP-Liberation#549]
### Is your feature request related to a problem? Please describe:

This feature request isn't necessarily related to a problem as in a bug, but more of a problem that I have found in gameplay, and that is base defense is too easy. It is simply annoying. For example, lets say you have a FOB, FOB Alpha. It gets attacked and you have 20 minutes to defend. Not a challenge, just spawn there and if you have a half decent FOB you can just keep respawning until you kill all of the enemies. Not difficult, just annoying.
### Describe the solution you'd like:

In order to fix the issue, I would like to suggest that when your FOB is under attack that you should not be able to spawn there, and instead have to travel there from some other location if you want to defend it. This would make base defense much more fun, difficult and relevant. It would also be nice if any other FOBs and mobile respawns within 1-2.5km were disabled.
### Additional context:

I don't have any screenshots to demonstrate this here, but I am sure that others will know what I am talking about.

**Comment by EvilSh4d0w** [comment]
very nice i appreciate this suggestion and would be happy about an implementation. but what you should pay attention to would be a defense by FOB construction AI set up to make possible.
I know that it is currently already possible to build stationary guns with crew but they often just watch and let the attackers shoot them calmly.
