### ISSUE TITLE
Expansion of Intel System

### ISSUE THREAD

**Issue by Phantom-LF** [KillahPotatoes/KP-Liberation#550]
### Is your feature request related to a problem? Please describe:

The feature Im requesting is an expansion of the intel system. It seems like the plan is that for 0.97 the old intel system would just me re-implemented, as said here: https://github.com/KillahPotatoes/KP-Liberation/issues/531. This is nice but I find that most of the time there are no surrendering AI, mostly because when I play we only have 3-6 guys in the AO. Because of this, we play on 1000%+ Alertness which can be frustrating wanting to decrease this but being unable to.
### Describe the solution you'd like:

What I would suggest is add the ability at any point to go on recon missions that would have the same affect as capturing someone, giving intel points, but always being available as an option. The amount would vary depending on location. For instance, if you are in friendly territory or in the middle of the ocean, you would not gain any. If you were by a radio tower or a small town you would gain 10-20. If you were by a capital you would gain 20-30, and if you were by a military base you would gain 30-40 intel points. 
### Additional context:

I don't have any screenshots to demonstrate this.

**Comment by Wyqer** [comment]
The #531 is about re-implementing the POW mechanic, yes.
But it's not a "with this the intel point gain is finished" task. The "short summary" is always the best way to see what the task is all about.
So don't worry, we've already some more ideas concerning intel during the mission. Personally I was also not very happy with the state that you can only gain intel by POWs and documents/laptops you could find at military bases.
