### ISSUE TITLE
Enemy Supply Lines

### ISSUE THREAD

**Issue by Phantom-LF** [KillahPotatoes/KP-Liberation#551]
### Is your feature request related to a problem? Please describe:

Something that would add a little bit more planning in thought into the game would be implementing enemy supply lines. 
### Describe the solution you'd like:

Just like guerrillas can attack yours, you can attack theirs resulting in them having less vehicles or maybe less men in the upcoming battle. You could also complete encirclements, such as encircling a military base which would make it unable to spawn more units after you killed them, even if you leave the area. For instance, let's say a town has a 50 man garrison. All surrounding tiles are captured, and you kill 40 of those guys. You come back an hour later and there should only be 10 guys left instead of the full garrison.
### Additional context:

I don't have any screenshots to demonstrate this feature request.

**Comment by Wyqer** [comment]
This is basically already planned/mentioned in #529, so I'll close this as duplicate.
In general it's the best, if you comment on dev-tasks which are connected to the suggestion you would like to mention (if there is one, of course). That way we keep it all at one place.
