### ISSUE TITLE
Settings for Ace-Arsenal isn't working right

### ISSUE THREAD

**Issue by madpat3** [KillahPotatoes/KP-Liberation#554]
### Basic Information

**Mission version:**
sprint 8
**Map used:**
altis
**Mods used:**
cba, ace
**Dedicated or local game:**
local (self hosted)
**Source of the mission file (URL):**
official

### Individual Things
**Did you edit anything within the mission files?**
no

**If yes, what did you edit exactly?**

### Short Issue Description
when you change the type of Ace-Arsenal via CBA-Settings, you cannot open the Ace-Arsenal. **And** you have to restart the mission, for those kind of settings to change at all.

### Expected Behaviour
In all types of Settings, Ace-Arsenal should be available in the way, it is set to. 

### Steps to Reproduce the Issue
Start the mission on Selfhosted Multiplayer.

Change Ace-Arsenal Settings from **Whitelist-Method to Unrestricted**, restart mission: (No Arsenal available and a Hint appears: "No Virtuell Item Available").  

Change Ace-Arsenal Settings from **Whitelist-Method to Blacklist-Method**, restart mission: (Arsenal available).

Change Ace-Arsenal Settings from **Unrestricted to Whitelist-Method**, restart mission: (No Arsenal available, but shows the "not allowed items" in a hint in first place. After opening the Arsenal, a Hint appears: "No Virtuell Item Available").

Change Ace-Arsenal Settings from **Unrestricted to Blacklist-Method**, restart mission: (Arsenal available).

Change Ace-Arsenal Settings from **Blacklist-Method to Whitelist-Method**, restart mission: (No Arsenal available, but shows the "not allowed items" in a hint in first place. After opening the Arsenal, a Hint appears: "No Virtuell Item Available").

Change Ace-Arsenal Settings from **Blacklist-Method to Unrestricted**, restart mission: (No Arsenal available and a Hint appears: "No Virtuell Item Available").

### Screenshots, Serverlog or any other helpful Information
![20181212034953_1](https://user-images.githubusercontent.com/15272840/49844109-e6f2fe00-fdc1-11e8-8352-93d0b9222af2.jpg)
![20181212035004_1](https://user-images.githubusercontent.com/15272840/49844110-e6f2fe00-fdc1-11e8-878f-6346f3ca7e59.jpg)

**Comment by Dubjunk** [comment]
fixed with #556
