### ISSUE TITLE
Switch the AI system to UPSMON

### ISSUE THREAD

**Issue by Havoc302** [KillahPotatoes/KP-Liberation#563]
### Is your feature request related to a problem? Please describe:

Problem is the AI are stupid. They just stand there barely responding to nearby fire. I understand this is an ARMA limition but UPSMON changes their behaviour drastically. Players who have played against UPSMON AI often comment that it's like fighting a group of well trained players.

### Describe the solution you'd like:

http://www.armaholic.com/page.php?id=21935
I'd like to see UPSMON implemented, it's used in a lot of popular mission systems like Antistasi and several that were written for Epoch and Exile.

**Comment by Wyqer** [comment]
We won't implement 3rd party scripts in the official Liberation releases or code. If you like the script, you're free to create a derivative (in respect to our license: [Small Summary/Explanation](https://github.com/KillahPotatoes/KP-Liberation/wiki/EN_licenseGuide)) and implement the script for your derivative or private use.

**Comment by Havoc302** [comment]
Ahh that's a pity, thanks for responding.
