### ISSUE TITLE
[1.90]Strange popup after Arma 3 1.90 update

### ISSUE THREAD

**Issue by GoldJohnKing** [KillahPotatoes/KP-Liberation#572]
### Basic Information

**Mission version:**
- v0.963a-Hotfix3
- v0.97 Sprint 10 Result

**Map used:**
- Altis

**Mods used:**
- CBA_A3
- ACE3
- ACEX
- TFAR
- RHSUSAF
- RHSAFRF
- ACE Compact RHS USAF
- ACE Compact RHS AFRF
- Enhanced Movement
- Arma III Chinese Localization Enhanced
- JSRS SoundMod
- JSRS SoundMod Reloading Sounds
- JSRS SoundMod RHS USAF Compact
- JSRS SoundMod RHS AFRF Compact
- Archilles

**Dedicated or local game:**
- Dedicated
- Local game not tested

**Source of the mission file (URL):**
- Github Release Pages

### Short Issue Description

😭 😭 😭
Another mission problem occured after the Arma 3 1.90 update...

I used to use H&M mission but it cause client crash after Arma 3 1.90 update, so I have to change the mission on my server, but while I use KP Liberation (v0.963a-Hotfix3 and v0.97 Sprint 10 Result both tested) and some self-made missions, an error dialog pops up once I get into the mission:

![107410_20190305192531_1](https://user-images.githubusercontent.com/26923626/53962392-ebf7ed00-4125-11e9-8b71-2da3a3d358d4.png)

I've deleted my server's profile both in server directory and user's "Documents" directory, but it still shows up. I wonder if there's something wrong with the compability of the Liberation mission and the Arma 3 1.90 update. I've used the v0.963a-Hotfix3 mission at 1.88 version before, everything goes well.

By the way, similar error dialog pops up if player use ShackTac User Interface (STUI) Mod.

### Steps to Reproduce the Issue
Just use 1.90 dedicated server to host the mission, and use a 1.90 client to join it, then the error occurs.

**Comment by Wyqer** [comment]
That's no critical error and only occur once during a session. It can be ignored.
It doesn't cause any issues.
If you want to "fix" it on your end:

At this line
https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/ui/standard_controls.hpp#L68

insert

    widthRailWay = 1;

And by the way a good first issue. Kept the template and provided all needed information. 👍

**Comment by GoldJohnKing** [comment]
Yep, got it.
But may I ask what "widthRailWay = 1;" do and why it happens? I'm really curious about it.

**Comment by Wyqer** [comment]
This attribute was obviously added in 1.90. Personally I haven't researched any further, why BI added this attribute to the map dialog control.
It's even not listed yet in the official Wiki: https://community.bistudio.com/wiki/Dialog_Control_Map

The error message is just "there is no value for the attribute `widthRailWay` in the used map control.
So the "fix" is to just provide a value for it, by adding that attribute to the class.

**Comment by GoldJohnKing** [comment]
OK, I got it. Thanks a lot for your patience, and have a nice day~ 😄
