### ISSUE TITLE
Add Liberate Human Trafficked Civilians Secondary Mission

### ISSUE THREAD

**Issue by mwpowellhtx** [KillahPotatoes/KP-Liberation#580]
## Liberate the Human Trafficked Civilians

We received intelligence that Opfor is trafficking civilians and we have been called to liberate them. The civilians will be transported in a container and guarded by Opfor forces.

### Additional context:

Setup the mission not unlike the Officer Hunt. In terms of cost/benefit, whatever makes sense, maintains balance, etc. Maybe costs 10 Intel, something like that. Could liberate let's say 5 or half a dozen civilians.

The civilians should be spawned in an openable container, hands in the air, not unlike the Civilian Intel when he spawns. (Although, sometimes, when the server is really being pushed, the Intel spawn is a repurposed resistance fighter, but this is another issue altogether, just be aware that the pool sometimes gets stressed out).

Assuming successful neutralization of Opfor forces, Blufor should capture (and/or tie) the liberated civilians can be loaded in a vic and returned to any FOB. (Transport should work like it normally does, load them in a vic, unit command them, redeploy with escorted civilian in hand, etc).

Killed civilians punish Blufor like normal, -5 per (or whatever the penalty is moving forward). Successfully liberated civilians benefit +3 Reputation per. Really, I want the penalty to punish as it normally does, but when Blufor is disciplined and successful at it, can further dig themselves out of Reputation holes.

Opfor forces can be modest, maybe a unit or two, not unlike the radio tower, or perhaps even pilot rescue.

May or may not impact the Alert level.

**Comment by tyl3r99** [comment]
good suggestion, good mission for reducing civilian hostility

**Comment by tyl3r99** [comment]
Another good one could be Officer assassination where we have to recon an area and manually find him as he could be trying to blend in i could make loads of missions just dont have the knowledge to put them into liberation

**Comment by Dubjunk** [comment]
As the latest stable release of the legacy framework won't get any more updates (beside of critical errors due to ArmA updates or similar) this could be integrated with the new 0.97.

It's planned to have a side missions framework but the missions itself aren't planned until now.
Maybe we'll collect some ideas in a later stage and provide some side missions, other missions should be easily added then.

But for now this will be closed.

**Comment by mwpowellhtx** [comment]
@Dubjunk Fair enough. How challenging is it to extend the secondary missions in the latest stable *0.963a*?

@tyl3r99 Basically already exists; when civilian approval is positive and green, you sometimes encounter a civilian intel. Go capture him and interrogate at a FOB. Sometimes he hands you an officer hunt. That's basically that. Successfully completing that knocks the alert level down 20%. You may also abscond with whatever gear and the unarmed vic (GAZ, for instance) that spawns with the objective.

**Comment by mwpowellhtx** [comment]
@Dubjunk Just to follow up, I think the template elements are basically "there" in the current most recent stable release, between civilians who spawn in surrendered (i.e. intel) to openable containers (i.e. at factories or bases), to spawning in units, i.e. radio towers, pilot rescue, etc. Just wanted to get an idea as to effort level. That being said, I'm deep diving into a clone of the repository for my unit, so either way, it's all good. Thanks!
