### ISSUE TITLE
Suggestion/Feature request: FPS target in player menu 

### ISSUE THREAD

**Issue by tyl3r99** [KillahPotatoes/KP-Liberation#583]
## Suggestion/Feature request
Add the FPS target from the original liberation as its very useful with maintaining a good fps rate in my opinion; as i could not see it in the newer dialog (S10)

 

### Is your feature request related to a problem? Please describe:
No

### Describe the solution you'd like:
FPS target value like in 0.963a

### Additional context:
http://prntscr.com/n8s7rg

**Comment by Wyqer** [comment]
Just as background information on the old "keep FPS" feature in the extended options.
It was kind of a "dynamic view distance adjustment". So basically if your frames dropped below X, it reduced your view distance until your FPS are again above or equal X.
So this was running all the time on the clients:
https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/GREUH/Scripts/GREUH_dynamic_view_distance.sqf

I won't promise that it'll get into the KP Player Menu (which is by the way also available as standalone for own missions), but we'll put it on our table for a discussion in the next planning phase.

**Comment by tyl3r99** [comment]
yeah it works very similar to the mod called "dynamic view distance" but it works better than that mod. 
Thanks! :)
