### ISSUE TITLE
Arsenal, Logistic, Permission documentation

### ISSUE THREAD

**Issue by Dubjunk** [KillahPotatoes/KP-Liberation#586]
### Short Summary
As a developer I want to ensure, that everyone can work with the framework. The target is that public functions can be found quickly and every module gets a short summary in a module ReadMe.

### Description
As the framework gets bigger and bigger, we want to start some documentation work.
The functions of a module, emitted and consumed events and so on.

### Sub-Tasks
- [ ] Arsenal docu
- [ ] Logistic docu
- [ ] Permission docu

**Comment by tyl3r99** [comment]
will this be where it will explain how to possibly create your own sidemissions? 💃

**Comment by Wyqer** [comment]
```sqf
if ("sidemission" in ["arsenal", "logistic", "permission"]) then {
     hint "yes";
} else {
     hint "no";
};
```

**Comment by tyl3r99** [comment]
apologies I mean in the readme's in general :)

**Comment by Wyqer** [comment]
Guess this could be considered as duplicate to #508
