### ISSUE TITLE
Suggestion/Feature request: Tree cutter

### ISSUE THREAD

**Issue by tyl3r99** [KillahPotatoes/KP-Liberation#589]
## Suggestion/Feature request

Tree cutter option for admin/commander at the FOB(s)

### Is your feature request related to a problem? Please describe:
no problem, just the current grass cutter in 0.963a only removes grass not trees

### Describe the solution you'd like:
Possibly implement either a tree cutter object if they even do them or a script that could clear tree around X distance called in the kp_liberation_config i.e. "tree_cutter_radius = 50;"

### Additional context:
for example antistasi has a similar feature and could come in handy when maybe building in a built up wooded area.

**Comment by Wyqer** [comment]
Basically done in v0.96.5 via the `create clearance` action for commander/admin.
