### ISSUE TITLE
Extend elite vehicle unlocking gameplay mechanic

### ISSUE THREAD

**Issue by Daeburon** [KillahPotatoes/KP-Liberation#591]
### Is your feature request related to a problem? Please describe:
No.

### Describe the solution you'd like:
right now elite unlocks happen by simply capturing the associated military zone. what if instead of it being automatically unlocked, an empty version of the vehicle is spawned there (as if its a prototype, or being serviced or something). players would need to be careful not to destroy the vehicle during their attack (thus limiting the use of bombs/mortars/arty) and after capturing the zone they then need to drive/fly/tow/slingload, etc the vehicle back to a FOB. the FOB could have a building, similar to the salvage yard, but this would be "Research Lab" or "Engineering Workshop" or something. players could then use an action similar to "recycle", but instead its "research". this would delete the vehicle, like recycle, but not give resources, instead this would unlock the item in the build menu. 

what do you think?

### Additional context:
perhaps other vehicles could be unlocked this way as well? I think a version of Liberation where you play as the GREENFOR and their more limited vehicle selection could be cool, and being able to unlock the BLUEFOR/OPFOR vehicles could be interesting for them. 

p.s. much thanks to Wyqer! ive been doing some editing on my own to playtest some other ideas, and like everyday im referring to years old threads where your replies are just what i need. youve been super helpful to me this week and you dont even know! cheers!

**Comment by Daeburon** [comment]
additional idea: maybe also make it a mystery what the elite vehicle is for each military zone. if this were the case, players might be inspired to do some actual meaningful recon. commanders might be motivated to send recon units to figure out which bases have which vehicles, and this might dictate their strategy for which order to attack which zones.

one downside I can see to the main idea, is that if the vehicle is destroyed, players wont be able to unlock it. maybe thats ok? if thats not ok, maybe there could be a secondary method to unlock elites, like using intel points or something? unlocking elite vehicles might be expensive to do via intel, so players are still motivated to try and capture it instead.

**Comment by Nopus64** [comment]
I like the idea behinde it. Maybe when you can transport there can also be a delay timer for studying the new "Vehicle". But i see the problem in Transporting. I tried to Slingload a Plane with the advanced slingloading mod. But they start fallying under the Chopper after a short time of flying. (i was slow like 80 km/h or so. So there could be maybe. A Box with blueprints in it. (So there could be a safer way to get the stuff back / Computer for Digital Plans, Boxes, and and and...). It also depends what dose Wyqer thinks about it.

**Comment by Wyqer** [comment]
Basically not a bad idea to extend this gameplay mechanic a little more. We won't implement it in 0.97.0, but keep it on our list for a "look at/discuss" for a version after 0.97.0.
