### ISSUE TITLE
Kill Manager - possible duplicate function

### ISSUE THREAD

**Issue by johnpool3** [KillahPotatoes/KP-Liberation#601]
I noticed on line 91 of `Missionframework/scripts/shared/kill_manager.sqf` that the function

 ```
if (side (group _unit) == GRLIB_side_friendly) then {
   stats_blufor_teamkills = stats_blufor_teamkills + 1;
};

if (side (group _unit) == GRLIB_side_friendly) then {
  stats_blufor_teamkills = stats_blufor_teamkills + 1;
};
``` 
appears twice.

Not sure if this is intended or a copy and paste error, just mentioning in case you weren't aware.

Also amazing mod, thank you for all the hard work with it!

**Comment by Wyqer** [comment]
The second entry should count for blufor soldiers killed. Somewhere in the past it was edited wrong. Fixed
