### ISSUE TITLE
Upgrading to 0.96.4 from 0.96.3 does not carry over save.

### ISSUE THREAD

**Issue by dinojc** [KillahPotatoes/KP-Liberation#609]
### Basic Information

**Mission version:**

**Map used: **
Altis

**Mods used: **
ace, ACE Compat - RHS Armed Forces of the Russian Federation, ACE Compat - RHS: GREF, ACE Compat - RHS United States Armed Forces, ACEX, ADV - ACE CPR, Advanced Towing, Bamse cTab Fix, CBA_A3, CH View Distance, cTab, CUP ACE3 Compatibility Addon - Terrains, CUP Terrains - CWA, CUP Terrains - Core, CUP Terrains - Maps, Enhanced Movement, Jbad, LYTHIUM, Project OPFOR, RHSAFRF, RHSGREF, RHSUSAF, ShackTac User Interface, task_force_radio, @UGL_Smoke_Fix_v1.0

**Dedicated or local game: **
Dedicated

**Source of the mission file (URL): **

Built from Master File using build.bat

### Individual Things
**Did you edit anything within the mission files?**
Yes

**If yes, what did you edit exactly?**
We have edited MissionParams.hpp to set the default values as we want. 
Description.ext we added the line cba_settings_hasSettingsFile = 1; at line 8.
kp_liberation_config.sqf edited only what factions each side is.

### Short Issue Description
we upgraded the dedicated server from 0.96.3 to 0.96.4 by following the instructions on the wiki which have stated to overwrite the files in the liberation folder. However once the server is loaded and we load in we start with a fresh save not the current save we are on. As well as once loaded in we spawn on an island and even after we select "join the fight" the menu closes and we still remain on the island.

### Expected Behaviour

Current save is loaded and players are able to select what fob we want to spawn at.

### Steps to Reproduce the Issue

1. Have a dedicated server with 0.96.3 loaded and have a save associated to it.
2. Upgrade the server to the new version and edit files as listeded above
3. launch server and load in.

### Screenshots, Serverlog or any other helpful Information

**Comment by Wyqer** [comment]
As stated on the release page, the comments in the Workshop files and in the BI Forums posting:
Saves from earlier versions aren't compatible with 0.96.4.
Use your 0.963a missionfile which should still load your save fine, if you haven't tried to modify or tinker with the save data.

**Comment by Wyqer** [comment]
I've added a small fix. Should be compatible. Just updating the rar files and workshop releases.
