### ISSUE TITLE
No Entry "bin/config.bin/cfgworlds.gm_weferlingen_summer."

### ISSUE THREAD

**Issue by Sp4mp** [KillahPotatoes/KP-Liberation#611]
Hello,

i connected to my Server and put the Commander Role. Than i click on "OK" and they say to me : "No entry bin/config.bin/cfgworlds.gm_weferlingen_summer."
Hope anyone can help me.

**Comment by veteran29** [comment]
You're either missing GM DLC on the server, client or on both. Verify your mod line for the server and check again.

Also GitHub is not a place for such type of support. Check out our Discord server for further assistance.
