### ISSUE TITLE
Add BASE FIRE FREE function

### ISSUE THREAD

**Issue by teemo0803** [KillahPotatoes/KP-Liberation#616]
# Add BASE FIRE FREE function to FOBs and Base

## functions are as follows:

#define SAFETY_ZONES [["RUSFOR", 50],["RESPAWN_Guer",50],["respawn_east",50]]

#define MESSAGE "weapon safe in base"
#define MESSAGE2 "you cant use this weapon"

if (isDedicated) exitWith {};
waitUntil {!isNull player};

//safe zone
player addEventHandler ["Fired", {
    if ({(_this select 0) distance getMarkerPos (_x select 0) < _x select 1} count SAFETY_ZONES > 0) then
    {
        deleteVehicle (_this select 6);
        titleText [MESSAGE, "PLAIN", 3];
    };
}];

**Comment by Pi123263** [comment]
Is this for the starting base or for FOB'S?
