### ISSUE TITLE
Dismounts in QRF not in vehicles

### ISSUE THREAD

**Issue by SomethingSimpl** [KillahPotatoes/KP-Liberation#622]
### Basic Information

**Mission version: latest**

**Map used: Chernarus Winter**

**Mods used: ACE, RHS, 3CB, DAGGER SNIPER MOD, CBA, CUP MAPS**

**Dedicated or local game: local**

**Source of the mission file (URL): official**

### Individual Things
**Did you edit anything within the mission files?**
No.

**If yes, what did you edit exactly?**
n/a

### Short Issue Description
Troop transports in QRF spawn with their troops outside -BMPs always arrive first empty and dismounts have to run long distances (presumably) from the spawn point.

### Expected Behaviour

Dismounts to exit vehicle closer to objectives.

**Comment by Dubjunk** [comment]
Any information about your used OPFOR preset and the exact classname of the BMP would be very helpful.

**Comment by SomethingSimpl** [comment]
Actually the default setup of your Chernarus Winter version - rha_afrf. And it doesnt seem to be tied to a specific version of BMP, rather I havent seen any troops ever actually being "delivered" by dismounting. Only running long distances from where they spawn long after the transport vehicle itself arrives.
