### ISSUE TITLE
Menus stopped working after server ran for 12hours+

### ISSUE THREAD

**Issue by Swearinbag** [KillahPotatoes/KP-Liberation#632]
### Basic Information

**Mission version:**
v0.96.4

**Map used:**
Altis

**Mods used:**
CBA_A3, RHSUSAF, RHSAFRF, RHSGREF, RHSSAF, JSRSSOUNDMOD, JSRSSOUNDMOD RHSAFRF, JSRSSOUNDMOD RHSUSAF, JSRSSOUNDMOD RHSGREF, ACE, ACE Compat RHS Gref, ACE Compat RHS USAF, ACE Compat RHS AFRF, Achilles, Gradrenches

**Dedicated or local game:**
Dedicated

**Source of the mission file (URL):**
https://github.com/KillahPotatoes/KP-Liberation/releases

### Individual Things
**Did you edit anything within the mission files?**
No

### Short Issue Description
Ingame menus near FOB's and respawns don't work anymore.

### Expected Behaviour
After a steady and fun gaming experience after 12 hours that the server was running, suddenly the menus ingame near the FOB's and respawn areas didn't work anymore. No build, Arsenal or extended menu options.

Is this a known issue?
Not that I'm aware of.

**Comment by veteran29** [comment]
It's known issue, it happens due to usage of scheduled runtime. It's recommended to restart the mission every 6-8 hours.
