### ISSUE TITLE
csat_apex missing a comma

### ISSUE THREAD

**Issue by aeiounr2** [KillahPotatoes/KP-Liberation#635]
### Basic Information

**Mission version:**
0.96.4
**Map used:**
Tanoa
**Mods used:**
ace,CBA_A3, Jsrs soundmod, advanced towing
**Dedicated or local game:**

**Source of the mission file (URL):**

https://github.com/KillahPotatoes/KP-Liberation/tree/master/Missionframework
### Individual Things
**Did you edit anything within the mission files?**
yes

**If yes, what did you edit exactly?**
changed blufor preset to csat_apex by changing the number in the kp_liberation_confing.sqf

### Short Issue Description
the game is completely broken, like explained in the faq when there is a missing comma
,due to a missing comma in line 115 of csat_apex.sqf between the vehicle name and the supply requirement

### Expected Behaviour

see above

### Steps to Reproduce the Issue

change preset to csat_apex

**Comment by Wyqer** [comment]
Deprecated/Duplicate
https://github.com/KillahPotatoes/KP-Liberation/commit/18ee1e7a2155b8e3cb16c88a95c379e9031ae6b7
