### ISSUE TITLE
production center storage removed after every restart

### ISSUE THREAD

**Issue by stabhappy** [KillahPotatoes/KP-Liberation#651]
version - 0.96.5

Map used - Livonia

Mods used - RHS AFRF, RHS USAF

I edited the opfor and blufor preset as well as the kp liberation config 

short desc - every time i leave the server and come back resources are not producing because the small storage placed inside the production center is removed for an unknown reason.

**Comment by Dubjunk** [comment]
See #645 for further information how to fix the bug until the next update will be released.
