### ISSUE TITLE
Desync on Dedicated Server

### ISSUE THREAD

**Issue by GrupoPhoenix** [KillahPotatoes/KP-Liberation#657]
## Bug Report

# Basic Information
(First of all: sorry for my english)
We are experiencing some desync with your mission on Dedicated server, the desync is between 0,5 seg to 1 seg and ocurs randomly between 15 and 50 segs. This is not the first Sandbox Insurgency we have made, we worked before with ALiVe only with some DropFPS.

**Mission version: Liberation Malden 0.96.5

**Map used: Malden

**Mods used: 2035 Russian Armed Forces, 3den Enhanced, Ace, Ace 3 extension (animations and actions), Ace 3 extension (Placeables), Ace Comapt RHS AFRF, Ace Compat RHS USAF, Ace Compat RHS GREF, ACEX, ADV ACE CPR, ADV ACE Splint, Advanced rapelling, Advanced towing, ASR AI3, Backpack on Chest, CBA_A3, CUP ACE3 Compatibility addon - terrains, Cup terrains core, Cup terrains Maps, Enhanced Movement, HiddenIdentityPack V2, JSRS Sound Mod, RHSAFRF, RHSGREF, RHSSAF, RHSUSAF, Specialist Military Arms, TFAR, VSM Collection, Zeus Enhanced.

**Dedicated or local game: Dedicated Server

**Source of the mission file (URL): https://github.com/KillahPotatoes/KP-Liberation

**Comment by Wyqer** [comment]
Check the size of your vars file on the server. Anything further to Discord.
