### ISSUE TITLE
Airdropping Purchased Vehicles

### ISSUE THREAD

**Issue by XefeWhiteFlye** [KillahPotatoes/KP-Liberation#659]
Here's a little thought that I was running along with.

Instead of having vehicles simply poof from the ether when you buy them, they would be airdropped to you at a specified location on a building that could be placed through the menu (like a helicopter pad or a composition) inside you FOB's build radius.

For example, you purchase an APC and have this LZ building placed somewhere at your FOB. Once the vehicle purchase is done and the landing zone is selected (Only if you have other LZ buildings at other FOB's on the map), a V-44 would spawn from a marked location at the carrier and fly towards the base selected. Depending on how much territory is yours versus the AI, the V-44 would take specific paths crossing over controlled towns and bases to avoid fire or take a long approach around enemy controlled areas. Once the V-44 is within range of the FOB and LZ, it 'drops' its cargo via parachute either onto or around the LZ site for the players to use from thereon. If there is no LZ building, you must designate a position on the map for the V-44 to drop its contents, but depending on your relationship with the resistance, they too can attempt to steal what was dropped and use it against you.

It's more for the immersion I guess but it was a suggestion none the less.

**Comment by XefeWhiteFlye** [comment]
I have done a little messing around with Achilles and found in the Zeus settings that you can set both an LZ and a supply drop, though they are one off. Could something like this be useful?

**Comment by VATICAN-PSYCHO** [comment]
Warlords, one of the MP modes, includes this feature.

**Comment by litrax** [comment]
Mmmhh. I personaly think airdropping is a nice thing. But I would suggest a single and consistent way of bringing in all bought vehicles. Airdropping the lighter ones on the one hand and spawning in HEMTT, tanks and other heavy vehicles on the other hand is NOT consistent. Further more some players may even wonder and be confused which way the vehicle that they actually bought would be delivered this time. And perhaps they start asking questions why that vehicle is delivered that way and the other vehicle is delivered the other way and if one could deliver tanks via airdrop and so forth and so forth. This could eventually leed in an endless discussion. Not that I am willing to discuss things  ;)
What do you think?

**Comment by XefeWhiteFlye** [comment]
You do have a point. To some degree there are vehicles that could suitably deliver each vehicle in game depending on it's size. It'd probably mean as well digging into other mods for larger vehicles to act as transports. Medium to heavy lift choppers could easily carry a variety of light vehicles but APC's and such I don't think would really work with the V-44 so you'd have to look towards possibly C-130's or just larger aircraft in general. You'd really need to go through each vehicle and assign a specific aircraft for its delivery based on its weight. Another thing to consider would be troops being brought in plus how aircraft being delivered would be handled.
