### ISSUE TITLE
Would like to whitelist permissions based on steamuid

### ISSUE THREAD

**Issue by Jason-Terry** [KillahPotatoes/KP-Liberation#661]
### Is your feature request related to a problem? Please describe:

As a admin, I would like to be able to white-list permission, per player, via steam uid.

### Describe the solution you'd like:

In order to make permission management of command slots far simpler, I feel a player uid whitelisting option would be great. This would be an ideal way to whitelist approved commanders without admin rights needed.

### Additional context:

If I am a milsim organizer / community dev I should be able to feed my mission a list of steamuid's and those uids should always be able to access the commander level permissions. This would be a great way to get rid of any scripted commandant slot, and allow for more dynamic and personal unit compositions to be created by the end user.

The only thing I think end users should have to worry about is.

1. If I am using ace are my player slots setup with medics and engineers.
2. ?? I can't currently think of any other worries we should have as a end user ??

**Comment by Wyqer** [comment]
To understand you correctly, you want this for the old framework?
And basically an array in e.g. the whitelist file which just is checked against if a player with given uid is in that list to get all "commander permissions"?
