### ISSUE TITLE
Multiple deploy points at beginning of new game

### ISSUE THREAD

**Issue by nifewavinsycho** [KillahPotatoes/KP-Liberation#667]
### Is your feature request related to a problem? Please describe:
I'm trying to make multiple redeploy points so when the game starts i would have a list that contains 
"operation base" 
"destroyer" 
"marine start point" and 
"naval yard"

I created small grasscutters and named them in in sequence so e.g.
startbase 
startbase1 
startbase2 
startbase3 

### Describe the solution you'd like:
Im quite the amateur that has managed to do some sucessfull editing e.g. adding additional buildable items and working on ui to get ace arsenal and max fob count but my knowledge (lack of) is giving me a headache, help would be much appreciated  i have been trying in scripts>client>spawn>redeploy_manager.sqf

Ive tried several ways of writing up line 20 and 86 in this file from 96.5 but unfortunatly i get to deploy and then spawn on the island

**Comment by Wyqer** [comment]
No need to ask this on Discord and opening an "issue", while deleting your message in Discord, some minutes after you don't get a reply there.

**Comment by nifewavinsycho** [comment]
Sorry i read up and someone stated they may get lost on discord and it would be best to try here so i figured best writing here rather than possibility of it getting lost
