### ISSUE TITLE
Cannot use High Command

### ISSUE THREAD

**Issue by mplorentz** [KillahPotatoes/KP-Liberation#670]
### Basic Information

**Mission version:** 0.96.5

**Map used:** Altis

**Mods used:** 
Advanced Towing
Advanced Sling Loading
Advanced Movement

**Dedicated or local game:** Dedicated

**Source of the mission file (URL):** Steam workshop

### Individual Things
**Did you edit anything within the mission files?** No

### Short Issue Description
When I play in the Commander slot I cannot command AI squads.

### Expected Behaviour

When hitting ctrl-space key I expect the high command bar to show up at the bottom of the screen, allowing me to select and command AI squads.

### Steps to Reproduce the Issue

1. Select commander slot when connecting to server
2. Spawn at FOB
3. Build an infantry squad from the BUILD menu
4. Hit ctrl-space to switch to high-command

### Screenshots, Serverlog or any other helpful Information
I know I can command squads through the Zeus interface, but I don't like the 3rd person camera that it gives me. I have seen someone use high command in KP Liberation Takistan ([youtube](https://www.youtube.com/watch?v=IowXiBxI3FI)) so I know at one point it was possible.

**Comment by Wyqer** [comment]
A great first issue by using the template. I really mean it, that's something many people aren't capable of.

Concerning your report: High Command from A3 was never part of Liberation, so no it was never possible, you're wrong. The video you've linked is from @woofer808 and he's using the mods `Advanced AI Command` and `C2`. Refer to the description he added to his video.

**Comment by mplorentz** [comment]
@Wyqer I have tried loading up Advanced AI Command and C2 also and I am still not able to command any squads. The High Command section of the C2 UI is empty, and I get no UI at all for Advanced AI Command.

Is A3 High Command missing from Liberation because it breaks something? Or has it just never been added? It seems weird to me that you can purchase AI squads but you can't command them fluidly within the game. 

I think I could jump into the editor and add it myself, but I'm mostly curious why it hasn't already been done. Would you want a PR if I get it working?

**Comment by veteran29** [comment]
The C2 mod should work just fine with Liberation, there is quite big community of players playing singleplayer Liberation with that mod.

For more help I suggest to go check their Discord and documentation:
https://c2mod.net/
