### ISSUE TITLE
0.97 Suggestion: AI Commando FOB

### ISSUE THREAD

**Issue by nicoman35** [KillahPotatoes/KP-Liberation#683]
### Additional context:

Suggestion / feature request for v.0.97
On higher difficulty levels, and at high enemy aggression levels (90%+), from time to time, how about the AI sends some high specialized team of infiltrators / saboteurs consisting of one to three infantry units, preferably at night. 
Tasks:
- infiltrate the FOB
- produce as much damage as possible with charges to supply depos, key buildings, valuable vehicles, etc.
- man and steal an armored vehicle, do as much as possible damage with it to nearby player units, unmanned vehicles, and buildings
- after a given time (5 minutes or so), extraction. If possible by using the stolen vehicle, and disappear into the darkness

My imagination is, that those units are dressed in dark clothes, armed with silenced weapons, behaving as stealthy as possible until entering FOB. Their skills should be elite. The detection range for friendly AI should be lower towards this units. And a hint for players of the FOB assault only given, if friendly AI detect those units, or, if not detected, the first damage is occurring.

I know that this suggestion would need a LOT of coding, and is no easy task. But before not saying anything, I thought I should suggest anyway.

**Comment by Eogos** [comment]
This sounds like something that would be good to add in here: https://github.com/KillahPotatoes/KP-Liberation/issues/672

**Comment by Wyqer** [comment]
Basically a duplicate part of the enemy commander plans we actually have. One example:
> Furthermore a first implementation of the mechanic, that the enemy won't directly know the positions of the players FOBs and may send out reconnaissance teams in the area where the players are progressing, to discover the FOB, so it would be a valid target for later counter attacks by the enemy commander. Until it's not discovered it shouldn't be a valid target.

Refs: #529 #574 #647
