### ISSUE TITLE
v0.97 Parameter suggestion / feature suggestion

### ISSUE THREAD

**Issue by nicoman35** [KillahPotatoes/KP-Liberation#688]
### Is your feature request related to a problem? Please describe:

'Problem': The game can not be lost.
Players are given infinite weapons, ammo, etc., the arsenal and unlimited number of respawns is everything one player needs to handle ANY size of OpFor.

### Describe the solution you'd like:

- Parameter option to turn off arsenal at FOBs (instead, the FOB should be a container for any weapon / ammo. You want some fancy weapon? Ammo? Grenades? Well, then use resources to create and store them at the FOB. FOB lost? Well - too bad, all your items are gone too.)
- Parameter for the carrier to disappear after a variable time. E.g. after 24 to 48 ingame hours. 'This is USS Freedom high command. Intel has detected an enemy strike fleet heading for our position. Eta. 6 hours. We will be leaving our current position and heading to safe territory within 2 hours. Good luck. Over and out.'
Parallel to that, when respawning, and no carrier, no FOB, and no mobile respawn is any longer avaliable -> spawn at a friendly settlement/base with a rebel weapon or pistol and a rebel outfit, if civ rep is above -50%. If not - game over!
You want to build a new FOB without having one? Well, capture some civilian orange repair Truck (thus loosing civ rep), and one time modify the truck to a FOB.

### Additional context:

Of course FOBs would have to memory the items stored inside in case of a server restart.

**Comment by Pi123263** [comment]
Ooh I really like the idea of the USS Freedom leaving, instead of just having it be 24/48/xyz hours it should have some amount of randomness to it though, so you cant necessarily plan for it.

**Comment by Wyqer** [comment]
Covered by #594 

Also I recommend to have a look at the current state and planning of 0.97. USS Freedom isn't used in 0.97
