### ISSUE TITLE
Save interval in parameters 

### ISSUE THREAD

**Issue by MrStonkus** [KillahPotatoes/KP-Liberation#692]
### Is your feature request related to a problem? Please describe:
 I have a littlte problem in all my Liberation missions.
I have a little mission stop for 0,3 sec about EXATLY every 20 seconds. For example I am running, and after each 20 seconds my moving stopping at very low of time, for 0,3 sec about.

I found a problem. My micro stops was because scenario saves progres every 20 seconds. I have changed value "_save_interval = 60;" in file \scripts\server\game\periodic_save.sqf and this micro stops right now are every 60 seconds. My game and these files in SSD, its very strange that ARMA3 uses very large amount of system resourses in this case.
### Describe the solution you'd like:
It would be good to have ability to set periodic save interval in parameters.

**Comment by Wyqer** [comment]
Could be moved to config file, yeah.
Concerning your issue with saving, check the size of your vars file. If it's really really big, this can cause such lag while saving.
Ref how to find it: https://community.bistudio.com/wiki/Profile

**Comment by MrStonkus** [comment]
> Concerning your issue with saving, check the size of your vars file. If it's really really big, this can cause such lag while saving.
> Ref how to find it: https://community.bistudio.com/wiki/Profile

Thank you very mutch. My var file was 5,5MB, after file delete problem has gone. 
P.S. Waiting for the new versions of missions. Nice job!
