### ISSUE TITLE
Vehicle skin selection for preset units

### ISSUE THREAD

**Issue by B-Knight49** [KillahPotatoes/KP-Liberation#693]
From what me and a buddy can tell, you can't set the skin of a vehicle inside of the presets file. For example, we want to give OPFOR a desert camo T-90 - but that doesn't seem to be possible.

Forgive me if this is actually possible; we've looked for about an hour now and can't find anything.

**Comment by veteran29** [comment]
This is not a forum. Please take such questions to Discord.

The vehicle skin can be easily customized by executing a script on it via objectInits. (refer to wiki)

**Comment by B-Knight49** [comment]
We asked the Discord and got no response. Ironically, an invalid issue (my bad) has gotten us further than research in the last hour or so. Thanks.
