### ISSUE TITLE
Player's nickname blacklist. Player's nickname protection list.

### ISSUE THREAD

**Issue by Varrkan82** [KillahPotatoes/KP-Liberation#696]
### Is your feature request related to a problem? Please describe:

It is usual problem for server administrator when users connecting with default system user names, or, sometimes, with abusive niicknames. Administrator need to ask every such user to change their profile name. Also, usually, servers has their own regular players list. So to prevent other users from using these regular players names it is good to have some system to check corresponding of a nickname to it's UID.
### Describe the solution you'd like:

It could to be two different arrays with a prohibited nicknames and with a protected nicknames (name, UID). These lists will be checked when user join the server. If joined username present in prohibited nicknames list - he should be kicked with a message of a kick reason (the message would be better to be able to change). If joined username present in protected list, but his UID not correspond to configured in that list - he should be kicked of the server with a message of a kick reason.
The lists, if it possible, will be better to do not include to the missions pbo files. It will be better to include it from userconfig folder by a separate files. This will allow to change the lists without rebuilding of a mission.
### Additional context:

I'm almost done this feature by myself by importing some code blocks from mission there it is already works to my initPlayerServer.sqf file. But my scripting skill is not enough to make it show the messages to users...

**Comment by Wyqer** [comment]
That kind of Server player black-/whitelist is out of scope for a mission framework.
There are many tools and/or scripts which let you have something similar, as it’s not hard at all to create this functionality. You can join the discord server and ask for help with your script, as you said you’re struggling with one implementation.
