### ISSUE TITLE
Mission Corrupt on Restart

### ISSUE THREAD

**Issue by graffo** [KillahPotatoes/KP-Liberation#705]
### Basic Information

**Mission version:** 1.96.146070

**Map used:** Lythium

**Mods used:**

@BMS | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1617973312
-- | -- | --
ace | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=463939057
ACE Compat - RHS Armed Forces of the Russian Federation | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=773131200
ACE Compat - RHS United States Armed Forces | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=773125288
ACE Compat - RHS: GREF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=884966711
Achilles | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=723217262
ADV - ACE Splint | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1291442929
Advanced Rappelling | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=713709341
Advanced Sling Loading | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=615007497
Advanced Towing | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=639837898
bCombat | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=314397752
CBA_A3 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
CUP Terrains - Core | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=583496184
Jbad | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=520618345
LYTHIUM | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=909547724
Project OPFOR | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=735566597
RHSAFRF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843425103
RHSGREF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843593391
RHSUSAF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843577117
task_force_radio | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=620019431

**Dedicated or local game:** Dedicated

**Source of the mission file (URL):** https://drive.google.com/open?id=1_t_0Fvrdqk0fZwxFlyQDB3t_KSEQPGqz

### Individual Things
**Did you edit anything within the mission files?**
Yes

**If yes, what did you edit exactly?**
Unlock Zeus, Ace Configs and put some starter vehicles

### Short Issue Description
Sometimes when you restart the server, the kp option menu like Arsenal, Secondary missions disappear, and actually when you destroy the fob, the tension level not lowered.

### Expected Behaviour

When you activate a secondary objective like "Fob Hunting", the mission has no cost and don't low the tension level.

### Screenshots, Serverlog or any other helpful Information

Error in expression <at_readiness
|| _resources_intel_old != resources_intel
|| _infantry_cap_old != >
  Error position: <resources_intel
|| _infantry_cap_old != >
  Error Undefined variable in expression: resources_intel
File mpmissions\__cur_mp.lythium\scripts\server\game\synchronise_vars.sqf..., line 52

Server Log: https://drive.google.com/open?id=1gvnhLoxUsR1EJxb0BwHUWz52d7p3sfR9

**Comment by veteran29** [comment]
You're using 0.96.4 which had a bug with corruption of intel value, this was fixed in [0.96.5](https://github.com/KillahPotatoes/KP-Liberation/pull/618). 

To fix the issue execute `resources_intel = 0;` on server via debug console.

It's advised to update to latest release to prevent this from happening again..
