### ISSUE TITLE
Limited Zeus Function Not Working as Intended

### ISSUE THREAD

**Issue by JHill29th** [KillahPotatoes/KP-Liberation#714]
### Basic Information

**Mission version:**
v0.96.6
**Map used:**
Tanoa
**Mods used:**
<pre>15:42:55                            ShackTac User Interface |                @stui |      false |      false |             GAME DIR | 6017b07d0a32d8dfb2015dd952868b5764015fd3 |  ab7edfbc | C:\Arma3_Game_Servers\Mods\@stui
15:42:55                                              @aceg |                @aceg |      false |      false |             GAME DIR | d4a7f5c534272cc464ab0b7fb69a970312f45a79 |  90bfa929 | C:\Arma3_Game_Servers\Mods\@aceg
15:42:55                          RHS: Serbian Armed Forces |                @rhss |      false |      false |             GAME DIR | e712376273e70ca9ac1ea68a6b2c3654e3179a86 |  c1197679 | C:\Arma3_Game_Servers\Mods\@rhss
15:42:55                                          RHS: GREF |                @rhsg |      false |      false |             GAME DIR | dcf9f46af60b6abc941c8b5dc06ad031c15eafc4 |  dc7d599d | C:\Arma3_Game_Servers\Mods\@rhsg
15:42:55                          RHS: United States Forces |               @rhsus |      false |      false |             GAME DIR | 22a11a80f1287809f28254072472f055d2875c33 |  8d53abc1 | C:\Arma3_Game_Servers\Mods\@rhsus
15:42:55        RHS: Armed Forces of the Russian Federation |               @rhsru |      false |      false |             GAME DIR | 0e0e336c4217a33a515de5bb1cffff80f4f0e3db |  e0346bec | C:\Arma3_Game_Servers\Mods\@rhsru
15:42:55                                             @aceru |               @aceru |      false |      false |             GAME DIR | 945fb65040dea577ce3a4b7af1ea4ecdb2f3ce21 |  b17eecc3 | C:\Arma3_Game_Servers\Mods\@aceru
15:42:55                                             @aceus |               @aceus |      false |      false |             GAME DIR | a4b256d2faad21ea99ee35ae5f154bd33753d38d |  29bb96e8 | C:\Arma3_Game_Servers\Mods\@aceus
15:42:55                  Task Force Arrowhead Radio 0.9.12 |                @tfar |      false |      false |             GAME DIR | 3028ba91015d709af11bfe12a4c851569d259050 |  ebed631c | C:\Arma3_Game_Servers\Mods\@tfar
15:42:55                 Advanced Combat Environment 3.12.6 |                 @ace |      false |      false |             GAME DIR | 51cca4bbb26be976f46cc89ad3d53f1a243bfbcf |  ccf3ed89 | C:\Arma3_Game_Servers\Mods\@ace
15:42:55                      Community Base Addons v3.13.0 |                 @cba |      false |      false |             GAME DIR | 61f3ee176e89e625b893e753136f200e70a7d9a6 |  3ecbe430 | C:\Arma3_Game_Servers\Mods\@cba
15:42:55                          Arma 3 Contact (Platform) |                enoch |       true |       true |             GAME DIR | 0d59242b58e23b2ede068fee2616d3e4be87376b |  71bb1cea | C:\Arma3_Game_Servers\battalion\enoch
15:42:55                                       Arma 3 Tanks |                 tank |       true |       true |             GAME DIR | 73ad2cd4eae68045cea7a7221caef9e6e955ae45 |  ff97ef57 | C:\Arma3_Game_Servers\battalion\tank
15:42:55                                     Arma 3 Tac-Ops |               tacops |       true |       true |             GAME DIR | c42217db4f55205cf6f0f05e2a5d8f24384cf638 |  cf74c5ae | C:\Arma3_Game_Servers\battalion\tacops
15:42:55                                 Arma 3 Laws of War |               orange |       true |       true |             GAME DIR | 5acbf43a6a9a45060e8fb9c973bffdf5923ec29c |  12b76d7a | C:\Arma3_Game_Servers\battalion\orange
15:42:55                                      Arma 3 Malden |                 argo |       true |       true |             GAME DIR | b09aeef5451d9f0d3d4a61e77179267a70ff6da6 |  2afda5f3 | C:\Arma3_Game_Servers\battalion\argo
15:42:55                                        Arma 3 Jets |                 jets |       true |       true |             GAME DIR | 5bfa24542528e0d2ccbaa89eee6b0b3d353e8d4e |  20520625 | C:\Arma3_Game_Servers\battalion\jets
15:42:55                                        Arma 3 Apex |            expansion |       true |       true |             GAME DIR | 430f7b474885b219790a57de4de3eea2fb15b448 |  5032127f | C:\Arma3_Game_Servers\battalion\expansion
15:42:55                                    Arma 3 Marksmen |                 mark |       true |       true |             GAME DIR | 23a8722eb5c8b4175c3103c877cc7822bf13dd9a |  d102ca49 | C:\Arma3_Game_Servers\battalion\mark
15:42:55                                 Arma 3 Helicopters |                 heli |       true |       true |             GAME DIR | 5c6a375b889b703d247e6f7134d0b4749be7d25d |  bee51663 | C:\Arma3_Game_Servers\battalion\heli
15:42:55                                       Arma 3 Karts |                 kart |       true |       true |             GAME DIR | d9d59f8a35c0c4cf9e1583f1d778f01a3843bb8f |  b421f4ed | C:\Arma3_Game_Servers\battalion\kart
15:42:55                                        Arma 3 Zeus |              curator |       true |       true |             GAME DIR | 48863ef9dd9aa7bca9c81544fc489dddc71f629a |  a8deee88 | C:\Arma3_Game_Servers\battalion\curator
15:42:55                                             Arma 3 |                   A3 |       true |       true |            NOT FOUND |                                          |           | 
15:42:55                                    Advanced Towing |               @adv_t |      false |      false |             GAME DIR | da39a3ee5e6b4b0d3255bfef95601890afd80709 |  11fdd19c | C:\Arma3_Game_Servers\Mods\@adv_t
15:42:55                             Advanced Sling Loading |              @adv_sl |      false |      false |             GAME DIR | da39a3ee5e6b4b0d3255bfef95601890afd80709 |  11fdd19c | C:\Arma3_Game_Servers\Mods\@adv_sl
15:42:55                                       LAMBS Danger |               @Lambs |      false |      false |             GAME DIR | da39a3ee5e6b4b0d3255bfef95601890afd80709 |  11fdd19c | C:\Arma3_Game_Servers\Mods\@Lambs
15:42:55                                   Achilles (1.2.2) |           @achillies |      false |      false |             GAME DIR | da39a3ee5e6b4b0d3255bfef95601890afd80709 |  11fdd19c | C:\Arma3_Game_Servers\Mods\@achillies
15:42:55                                       @29th_Server |         @29th_Server |      false |      false |             GAME DIR | da39a3ee5e6b4b0d3255bfef95601890afd80709 |  11fdd19c | C:\Arma3_Game_Servers\Mods\@29th_Server
</pre>
**Dedicated or local game:**
Dedicated
**Source of the mission file (URL):**

https://github.com/KillahPotatoes/KP-Liberation/releases/download/v0.96.6/kp_liberation.Tanoa.zip
### Individual Things
**Did you edit anything within the mission files?**
Yes

**If yes, what did you edit exactly?**
Just set-up stuff in `mission_params.hpp`, `kp_liberation_config.sqf`, `whitelist.sqf`

### Short Issue Description
The limited Zeus parameter does not seem to function correctly.  Whether enabled or disabled, the create entity section of the curator interface does not populate.

### Expected Behaviour

Disabling limited zeus should allow full zeus capabilities.

### Steps to Reproduce the Issue

Set the limited zeus parameter to either enabled or disabled and launch the scenario.

### Screenshots, Serverlog or any other helpful Information
Server Log: https://www.dropbox.com/s/n7osqs1qc7idem6/arma3server_x64_BATTALION_2019-12-23_15-42-42.rpt?dl=0
![20191223143112_1](https://user-images.githubusercontent.com/10557046/71381571-49640a00-2591-11ea-8b63-197128c3c161.jpg)

**Comment by JoramD0** [comment]
I am having the same issue, however it for me is intermittent (seems random, cant make sense of it).
Mods list: 
```RHSAFRF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843425103
RHSUSAF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843577117
CBA_A3	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
RHSGREF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843593391
USAF MOD Main Pack	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1891346714
RHSSAF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843632231
USAF MOD Fighters Pack	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1891343103
USAF MOD Utility pack	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1891349162
ACEX	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=708250744
Advanced Sling Loading	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=615007497
Advanced Towing	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=639837898
Advanced Urban Rappelling	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=730310357
BackpackOnChest	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=820924072
Enhanced Movement	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=333310405
Jbad	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=520618345
LYTHIUM	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=909547724
Project OPFOR	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=735566597
NIArms All in One	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1208517358
Zeus Enhanced	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1779063631
(Unofficial) Advanced Combat Environment 3 modified for FlyViking Warfare Division	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1938478835
Theseus Services	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=646999497
```

Client/Server logs:
https://gist.github.com/JoramD0/c83dab7b58c51feef52887a6e351f16e

**Comment by veteran29** [comment]
When you're having this problem can you edit/delete/move (etc.) the objects?

**Comment by JoramD0** [comment]
I don't know about @JHill29th but I can edit/delete/move objects around. It's like it just doesn't add any objects/modules to the "create" menu.

**Comment by JHill29th** [comment]
> ... the create entity section of the curator interface does not populate.

When I submitted this issue I had assumed that the limited zeus would also allow or disallow create entity, not just the edit entity.  I hadn't thought that the ability to create might be limited although the ability to edit would be allowed.

**Comment by JoramD0** [comment]
https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/scripts/server/init_server.sqf#L140

After some testing it seems like this variable is applied but not loaded in zeus. I tried finding something to "reload" zeus but couldn't find much.

**Comment by Wyqer** [comment]
Just tried to reproduce the issue with a fresh 0.96.6 Altis PBO from the releases. No mods loaded and fresh save. Started as local MP session. Can't reproduce the issue. Working fine on my end.

Just to make sure that:
* You're playing 0.96.6.
* You haven't edited the mission.sqm via the editor like adding zeus modules or editing the existing one.
* You're joining as commander.
* At the `map screen -> Mission Parameters -> Active` you see that the parameter for limited zeus is disabled.
* You're opening the zeus interface.
* Everything on the right panel is empty.

If all of that is true, it's different from my test with no current obvious cause. So it would be helpful if you create a small video which shows all the above steps and that you've the described issue at the end.
