### ISSUE TITLE
Scalar Nan

### ISSUE THREAD

**Issue by graffo** [KillahPotatoes/KP-Liberation#717]
### Basic Information

**Mission version:** 1.96.146070

**Map used:** Lythium

**Mods used:**

@BMS | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1617973312
-- | -- | --
ace | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=463939057
ACE Compat - RHS Armed Forces of the Russian Federation | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=773131200
ACE Compat - RHS United States Armed Forces | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=773125288
ACE Compat - RHS: GREF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=884966711
Achilles | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=723217262
ADV - ACE Splint | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1291442929
Advanced Rappelling | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=713709341
Advanced Sling Loading | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=615007497
Advanced Towing | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=639837898
bCombat | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=314397752
CBA_A3 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
CUP Terrains - Core | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=583496184
Jbad | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=520618345
LYTHIUM | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=909547724
Project OPFOR | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=735566597
RHSAFRF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843425103
RHSGREF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843593391
RHSUSAF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843577117
task_force_radio | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=620019431

**Dedicated or local game:** Dedicated

**Source of the mission file (URL):** https://drive.google.com/open?id=1_t_0Fvrdqk0fZwxFlyQDB3t_KSEQPGqz

### Individual Things
**Did you edit anything within the mission files?**
Yes

**If yes, what did you edit exactly?**
Unlock Zeus, Ace Configs and put some starter vehicles

### Short Issue Description
Cannot build nothing, the vale of cronstruction stay on scalar nan

### Expected Behaviour

Construction value is scalar nan

### Screenshots, Serverlog or any other helpful Information

https://steamuserimages-a.akamaihd.net/ugc/778493000469004106/BEA34181FD119EDF0945A63E082C05EB50F909C7/?imw=1024&imh=576&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true

**Comment by veteran29** [comment]
This an issue with your edits most likely, provider server and client RPT.

**Comment by graffo** [comment]
> 
> 
> This an issue with your edits most likely, provide server and client RPT.

Last Server RPT https://drive.google.com/file/d/1zE0p56cSXJIBFW8A8Di0Dsxzb5GI2VUG/view?usp=sharing

**Comment by Wyqer** [comment]
* Server is running way too long (the log alone is more than 500,000 lines)
* Derivative which is based on 0.96.4 (old)
```
Mission file: [BMS]Liberation
[KP LIBERATION] [MISSIONSTART] Name: CTI 34 KP Liberation Lythium v0.96.4
```
* Issues with zeus edits from your side
```
Error in expression <(_this select 0) addcuratoreditableobjects (_this select >
  Error position: <addcuratoreditableobjects (_this select >
  Error Type Object, expected Array
```
* Issues with some own script or mod
```
Error in expression < select 0;

if ((_priors select _cause)>_priorCur) then
{
_dangerCause = _cause;>
  Error position: <_priorCur) then
{
_dangerCause = _cause;>
  Error Undefined variable in expression: _priorcur
```
Use the latest stable build for your derivative. For further help on issues like these, ask in the Discord support channels.
The issue tracker on GitHub is for issues with our releases not for "how to edit" or "how to create derivatives".
