### ISSUE TITLE
Missing Prisioners

### ISSUE THREAD

**Issue by LuizBarros99** [KillahPotatoes/KP-Liberation#722]
### Basic Information

**Mission version:**
v0.97 S14
**Map used:**
Altis
**Mods used:**

25th VAS - Growling Dogs - JetX, 3den Enhanced, ACE3, ACE 3 Extension (Animations and Actions), ACE Interaction Menu Expansion, ACEX, Advanced Ropes, Arma 3 editor goodies, AWESome : Aerial Warfare Enhanced Somehow, BackpackOnChest, Blastcore Edited (standalone version), CH View Distance, Diwako's ACE Ragdolling, Eden Extended Objects, Enhanced Movement, GRAD Trenches, Grenade Window Breaker(mod version), Ladder Tweak, LAMBS_Danger.fsm, LAMBS_RPG, LAMBS_Suppression, LAMBS_Turrets, LOGIC FSM, Prone Launcher, ShackTac User Interface, Swim Faster, Weapon Eventhandler Framework version 1.2, Zeus Enhanced
**Dedicated or local game:**
Local
**Source of the mission file (URL):**

From the STEAM Workshop "v0.97 Preview"
https://steamcommunity.com/sharedfiles/filedetails/?id=1578389037
### Individual Things
**Did you edit anything within the mission files?**
Yes.

**If yes, what did you edit exactly?**
Changed a few classnames of some enemy units (basically just really replaced snipers with sharpshooters)

### Short Issue Description
Captive enemies disappear when the sector is captured.

### Expected Behaviour

Captive enemies should not disappear when the sector is captured.

### Steps to Reproduce the Issue

Go within the activation range of an enemy sector.
Get one enemy to be ACE unconcious.
Capture this enemy.
Kill/delete all other enemies.
Capture the sector.
Try to find the previously captured enemy.

### Screenshots, Serverlog or any other helpful Information
Sorry, don't know how to find those.

**Comment by LuizBarros99** [comment]
I would also like to add that vehicles and eventual captives also disappear once the sector deactivates.  (AKA whenever you are bringing them back to your base)
 I would suppose that they MAYBE might also disappear when the sector is captured.

I'm bringing this up because I suppose that this might be related to the original issue I reported, or at least a very similar issue that has identical solution to my original post.

**Comment by Dubjunk** [comment]
Is it also happening for captives from surrendered enemies?

**Comment by LuizBarros99** [comment]
> Is it also happening for captives from surrendered enemies?

I don't think it happens, because IIRC enemies only surrender after you capture the sector (which is when I lose the ACE captives)

**Comment by syncy34** [comment]
> Is it also happening for captives from surrendered enemies?

Yes it is.

Yesterday we captured Syrta. We had 3 Enemies that surrendered.
We used ACE Cablewires and after around 5 minutes the first one despawned while escorting.
The second one despawned in the car, on the way back to our FOB. One was left at the end.
Most of the time we did not get a single one back to our FOB.
