### ISSUE TITLE
Problem with scroll wheel menus

### ISSUE THREAD

**Issue by Samuelogle99** [KillahPotatoes/KP-Liberation#728]
### Basic Information

**Mission version:**

**Map used:**
Staszow Poland, https://steamcommunity.com/sharedfiles/filedetails/?id=1432941733
**Mods used:**
Enhanced Movement
CBA_A3
Cup terrains - core
Ace
IFA3-AIO_LITE
ACEXC
Secret weapons
faces of war
GEIST-A3 LITE
Achilles
Immersion Cigs
Acoustic Guitar Mod

**Dedicated or local game:**
Dedicated
**Source of the mission file (URL):** https://steamcommunity.com/sharedfiles/filedetails/?id=1432941733

### Individual Things
**Did you edit anything within the mission files?**
I added some crates with the debug console command

**If yes, what did you edit exactly?**
and I tried to change the civ reputation which didnt work at all.

### Short Issue Description
The Issue is I can spawn at my fobs and scroll wheel but nothing comes up like build, arsenal redeploy etc. It used to be ok but i tried restarting my dedicated server cause I couldn't build anything because it said SaclarNaN in the bottom of the supplies preview. Now in the dedicated server console it is saying this:

### Expected Behaviour

I should be able to scroll

### Steps to Reproduce the Issue

Error Undefined variable in expression: kp_liberation_civ_rep
12:19:29 File mpmissions__cur_mp.staszow\scripts\server\game\save_manager.sqf..., line 683

This was after i tried resetting the civ rep with the command (which didnt work either)

12:18:49 Error position: <KP_liberation_civ_rep, KP_liberation_cle> 12:18:49 Error Undefined variable in expression: kp_liberation_civ_rep 12:18:49 File mpmissions\__cur_mp.staszow\scripts\server\game\save_manager.sqf..., line 683 12:18:51 Error in expression <liberation_convoy_ambush_inProgress && (KP_liberation_civ_rep <= -25) && (((_x s> 12:18:51 Error position: <KP_liberation_civ_rep <= -25) && (((_x s> 12:18:51 Error Undefined variable in expression: kp_liberation_civ_rep 12:18:51 File mpmissions\__cur_mp.staszow\scripts\server\resources\manage_logistics.sqf..., line 303 12:18:51 Error in expression <liberation_convoy_ambush_inProgress && (KP_liberation_civ_rep <= -25) && (((_x s> 12:18:51 Error position: <KP_liberation_civ_rep <= -25) && (((_x s> 12:18:51 Error Undefined variable in expression: kp_liberation_civ_rep 12:18:51 File mpmissions\__cur_mp.staszow\scripts\server\resources\manage_logistics.sqf..., line 303 12:19:09 Error in expression <,

**Comment by Pi123263** [comment]
Which resource is the ScalarNaN being shown for?

**Comment by Samuelogle99** [comment]
It was being shown on All of them when accessing the build menu. But the updated problem is that I cant even access any menu at all...

**Comment by Pi123263** [comment]
Try using dev commands to reset all the resources to 0

**Comment by Samuelogle99** [comment]
Thats no longer a problem, as I cant scroll wheel to do ANYTHING anymore

**Comment by Pi123263** [comment]
That can be caused by the resources not having an actual value

**Comment by Samuelogle99** [comment]
Ok I try that

**Comment by Samuelogle99** [comment]
Could you tell me the Dev command?

**Comment by Pi123263** [comment]
From the discord:

// GLOBAL VARIABLES
// Handled on the server, so need to be changed via exec server

// "Alert Level"
combat_readiness

// Intel points
resources_intel

// CivRep
KP_liberation_civ_rep

// Guerilla strength (determine their tier)
KP_liberation_guerilla_strength

// ------------------------

// RESOURCE SPAWN
// Exec local, spawns the according crate at player position.

// Supplies:
[] call f_createCrate;

// Ammo:
[KP_liberation_ammo_crate] call f_createCrate;

// Fuel:
[KP_liberation_fuel_crate] call f_createCrate;

// ------------------------

// Safe CivRep Changing (use this instead of direct global variable change)
// Needs to be executed on the server/host
// _amount can be positive or negative to add/substract the given value
[_amount] call F_cr_changeCR;

**Comment by Wyqer** [comment]
That's an old derivative from 2018 which doesn't use the actual framework. Contact the author of that derivative to update his version or fix his bugs. As it's not with the actual version from this repository, the issue report is redundant here.
