### ISSUE TITLE
RHSUSAF CH-53 Crates are in the wrong position.

### ISSUE THREAD

**Issue by Conep** [KillahPotatoes/KP-Liberation#731]
![20200229052933_1](https://user-images.githubusercontent.com/61619235/75609476-e15b1280-5b43-11ea-8f59-169882ac937f.jpg)
### Basic Information

**Mission version:**
KP_TakistanACRE
**Map used:**
Takistan
**Mods used:**
9Liners & Notepad | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1210050323
ace | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=463939057
ACE 3 Extension (Animations and Actions) | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=766491311
ACE Compat - RHS Armed Forces of the Russian Federation | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=773131200
ACE Compat - RHS United States Armed Forces | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=773125288
ACE Compat - RHS: GREF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=884966711
ACE Interaction Menu Expansion | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1376867375
ACEX | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=708250744
Achilles | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=723217262
ACRE2 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=751965892
CBA_A3 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
CUP Terrains - Core | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=583496184
CUP Terrains - Maps | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=583544987
Enhanced Movement | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=333310405
Enhanced Soundscape | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=825179978
F-15 Eagle | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=582478120
FA-18 Super Hornet | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=743099837
FIR AWS(AirWeaponSystem) | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=366425329
FIR Pilot&Crew Pack | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=433566590
JSRS SOUNDMOD | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=861133494
JSRS SOUNDMOD - RHS AFRF Mod Pack Sound Support | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=945476727
JSRS SOUNDMOD - RHS GREF Mod Pack Sound Support | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1180534892
JSRS SOUNDMOD - RHS USAF Mod Pack Sound Support | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1180533757
MCC Sandbox 4 - Mission Making The Easy Way | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=338988835
Philippine Army Uniforms | Local | http://www.armaph.net
Project OPFOR | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=735566597
RHSAFRF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843425103
RHSGREF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843593391
RHSSAF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843632231
RHSUSAF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843577117
ShackTac User Interface | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=498740884
USAF MOD Fighters Pack | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1891343103
USAF MOD Main Pack | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1891346714
USAF MOD Utility pack | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1891349162
USS Nimitz | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=643530417

**Dedicated or local game:**
Dedicated
**Source of the mission file (URL):**
Recent Github link for KP_ACRE

### Individual Things
**Did you edit anything within the mission files?**
Yes, rhs_usaf_des preset

**If yes, what did you edit exactly?**
Added vehicles included in RHS that are otherwise not included in the Vanilla release of KP GitHub

### Short Issue Description
When crates are loaded into the CH53, the create position is outside of the body.

### Expected Behaviour

When crates are loaded into the CH53, the create position should be within the fuselage.

### Steps to Reproduce the Issue

Open Eden editor, force Zeus mode, plop down the CH53, plop down a supply crate, edit the init field of the CH53 and paste the following; ["rhsusf_CH53E_USMC_D", -11.0, [0,2.5,1.4]]
Use the attach to line to attach the crate to the CH53.

### Screenshots, Serverlog or any other helpful Information
![20200229180957_1](https://user-images.githubusercontent.com/61619235/75605890-f2932780-5b21-11ea-8987-135d3b1d14fa.jpg)

![20200229052933_1](https://user-images.githubusercontent.com/61619235/75609481-f59f0f80-5b43-11ea-9526-b57440577b10.jpg)

**Comment by veteran29** [comment]
Fixed in 6fe4f99935a5ee1e943e4e654ecf7c0add34f750 will be available with 0.96.7 update.

**Comment by Conep** [comment]
Thanks for the update veteran29
