### ISSUE TITLE
Suggestion - Field Fortifications

### ISSUE THREAD

**Issue by Astrocat2374** [KillahPotatoes/KP-Liberation#734]
### Is your feature request related to a problem? Please describe:

I normally work in a small group and we mostly use AI to strengthen our forces. We normally set up a rally point, and move logistic vehicles and reserve forces to it. However, what normally ends up happening to us is the AI will launch a counter attack which will end up moving towards our position and decimating our exposed rally point, or a roaming tank will simply cut down all of our forces.
### Describe the solution you'd like:

Adding a vehicle or modifying one (Perhaps the Bobcat) to allow a small portion of fortifications to be built without having to deploy an FOB.
Fortifications may include:
-Hesco Barriers
-Hesco Barrier Towers
-Sandbag Walls
-Camo Nets
-Portable Lights
-Tents (Mostly to work with ACE Medical buildings)
-Helipads
-Helipad Lights
-Some additional aesthetic items like cargo pallets, tables and chairs

Static emplacements like HMGs, GMGs, and Titan Launchers would just be built at the FOB and transported, most likely in backpack form.
### Additional context:

We don't build a FOB for a number of reasons. One of the biggest is that a FOB requires a 200 meter distance between itself and another zone. Typically, we put our rally point within an already captured zone and I suspect many players do the same. Additionally, when an enemy comes into the vicinity of the FOB (sometimes just a single infantry unit) the FOB becomes compromised and we have to call off the attack to find someone sitting in a bush. Finally, a FOB spawns in a large building and requires space for that. My idea involves fortifying already existing buildings to decrease the amount of time and resources needed for preparation.

**Comment by Wyqer** [comment]
I would recommend that you add a script or mod (R3F logistics should do what you want). This would most likely not be added to the legacy framework anymore. Maybe this could be reconsidered in the rewrite, but that's still far away due to our current reliabilities outside of Arma modding/scripting.
So I'll close this for now but it'll stay in the issue list, so maybe it could be referenced and reopened later again.
