### ISSUE TITLE
Flickering Mobile Respawns

### ISSUE THREAD

**Issue by ashleystarburst** [KillahPotatoes/KP-Liberation#748]
### Basic Information

**Mission version:**
0.96.6
**Map used:**
Altis
**Mods used:**
CBA_A3, Vcom AI 3.3.3, LAMBS_Danger.fsm, LAMBS_RPG, LAMBS_Suppression, LAMBS_Turrets, CSW XM8 Pack, FA-18 Super Hornet, CROMOD VHS-2 Rifle, UTS-15 Shotgun, Specialist Military Arms, CZ BREN 2, Project Infinite - All in one, Project Infinite - Attachments CBA_A3, The CSAT Modification Project, The CSAT Modification Project (Replacement), RM Splinter Gear, Enhanced Soundscape, Enhanced Movement, Advanced Urban Rappelling, Advanced Sling loading, Advanced Towing, Advanced Rappelling, Arsenal Search, Walkable Moving Objects, VoyagerCompass HUD lite, Vana - Loadout Management (alpha), MRB Air Visiblity, MRB Vehicle Visibilty, Immerse, Ladder Tweak, Enhanced Video Settings. 
**Dedicated or local game:**

**Source of the mission file (URL):**

https://steamcommunity.com/sharedfiles/filedetails/?id=878714108
### Individual Things
**Did you edit anything within the mission files?**
No

**If yes, what did you edit exactly?**
N/A

### Short Issue Description
Mobile Respawns such as the Huron or the Hemtt Medical dissapear and reapear on the map (Their icon will flicker in and out of existence on their position where they have been driven to), and then when trying to respawn, their entry in the respawn menu will flicker in and out.  Respawning is still possible but it requires awkward timing to double click the entry in the respawn menu, sometimes accidentally leading to respawning elsewhere and using up your Mobile respawn time out. 

Note that this does not reliably happen all the time, to all players at the same time.  It is intermittent and seemingly random. 

### Expected Behaviour

To be able to spawn on the mobile respawn with no issues, and have no issues seeing the entry in the respawn menu. 

### Steps to Reproduce the Issue

1. Purchase mobile respawn
2. Drive to some location, near an objective such as a town
3. Die or manually force respawn
4. Go to respawn menu
5. Try to select Mobile respawn

**Comment by Wyqer** [comment]
Already fixed for next update.
