### ISSUE TITLE
Sling loading fob container on dedicated server next to impossible

### ISSUE THREAD

**Issue by Raskil** [KillahPotatoes/KP-Liberation#752]
Hi,

we are experiencing trouble with the sling load of the FOB container. While this works easily for myself when I host the game, it's next to impossible on a dedicated server. At some point in time the container seems to just "stuck" in the air and then the rope cuts.
I've found the following artice mentioning that slingloaded items shoult be handed over to the client of the pilot: https://forums.bohemia.net/forums/topic/215443-slingloading-and-latency-problems/
But I'm not sure if that is applicable in this case.

Regards

Raskil

**Comment by Wyqer** [comment]
The template isn't meant to be deleted, it's meant to be filled. Normally we close issues which doesn't follow this without further comment.

Already implemented for the next update.
https://github.com/KillahPotatoes/KP-Liberation/blob/v.0.96.7/README.md#0967-tbd
