### ISSUE TITLE
Persist supplies in conquered areas

### ISSUE THREAD

**Issue by bux** [KillahPotatoes/KP-Liberation#766]
### Is your feature request related to a problem? Please describe:
When playing with just a small group it isn't always feasible to secure an area, fend off any reinforcement and afterwards fetch all the supplies and deliver them back to a FOB. Supplies unfortunately don't spawn again when restarting the server.

### Describe the solution you'd like:
Have unclaimed supply crates (supplies, ammo, fuel) persist and spawn again when loading the mission.

### Additional context:
None

**Comment by bux** [comment]
That was fast. Thank you.

**Comment by Wyqer** [comment]
Wasn't much needed to implement this and the request makes sense, so you're welcome. 👍
