### ISSUE TITLE
[Feature request] Carry resources instead of "Push" function

### ISSUE THREAD

**Issue by tyl3r99** [KillahPotatoes/KP-Liberation#780]
## Suggestion/Feature request
**Carry resources instead of "Push" function**
### Is your feature request related to a problem? Please describe:

I'm always frustrated when using the vanilla game without the use of ACE, we cannot carry resource crates and it can be, very slow to push the crates over a long distance (i.e. your first dob supply drop)
### Describe the solution you'd like:

The ability to carry resource crates like when using the ACE mod, but in the vanilla game.
### Additional context:

Maybe a "AddAction function that says "Carry" // "Drop"

**Comment by veteran29** [comment]
Merged into v0.96.8 branch
