### ISSUE TITLE
[Minor bug] RPT description.ext error (max players)

### ISSUE THREAD

**Issue by tyl3r99** [KillahPotatoes/KP-Liberation#784]
### Basic Information

**Mission version:**
0.96.7
**Map used:**
Chernarus non 2020
**Mods used:**
RHSUSAF, RHSAFRF, JSRS, armaFXP, CUP maps, CUP core, Enhanced movement, CBA
**Dedicated or local game:**
Locally hosted
**Source of the mission file (URL):**

https://github.com/KillahPotatoes/KP-Liberation/archive/master.zip
### Individual Things
**Did you edit anything within the mission files?**
config file only

**If yes, what did you edit exactly?**
blufor, opfor, ind, civ presets 
unit caps etc

### Short Issue Description
Noticed something in my rpt when looking up an issue i had caused with adding some classnames to the blacklist category

### Screenshots, Serverlog or any other helpful Information

[Arma3_x64_2020-05-10_22-12-22.zip](https://github.com/KillahPotatoes/KP-Liberation/files/4606763/Arma3_x64_2020-05-10_22-12-22.zip)

22:15:01 Mission kp_liberation.chernarus: Number of roles (37) is different from 'description.ext::Header::maxPlayer' (34)

**Comment by Wyqer** [comment]
That's fine. The description.ext states 34 players, while there are 34 playable slots + 3 headless client slots. Don't cause any trouble in general, just adjust the number in the description.ext, if you want to remove that message.

**Comment by tyl3r99** [comment]
I did think that but wasnt 100% sure. Thank you for clarifying!
