### ISSUE TITLE
[0.96.7] Sector doesn't spawn enemies, after sector cap was reached

### ISSUE THREAD

**Issue by bux** [KillahPotatoes/KP-Liberation#788]
### Basic Information

**Mission version:**
v0.96.7

**Map used:**
Altis

**Mods used:**
![image](https://user-images.githubusercontent.com/1235520/82135582-9d9fad00-9804-11ea-8dd8-5f6bb12452b1.png)

**Dedicated or local game:**
Dedicated

**Source of the mission file (URL):**

https://github.com/KillahPotatoes/KP-Liberation/releases

### Individual Things
**Did you edit anything within the mission files?**
Params, Uniforms of player slots

### Short Issue Description
At some point no enemies spawn in sectors. The sectors can't be captured.
The indicator on the right is completely blue.

### Expected Behaviour

Enemies should spawn and after defeating them the sector should be captured

### Steps to Reproduce the Issue

No idea. The people on the server seemed to have used HALO to insert. Maybe a weird state after people teleport (halo) close to the sector?
Server was running for 4h 30m before this issue got reported.
This doesn't seem to happen all the time

Restarting the server fixes the issue. _but this can't be the solution to restart after only 4h 30m_

### Screenshots, Serverlog or any other helpful Information
![20200517060418_1](https://user-images.githubusercontent.com/1235520/82135659-6d0c4300-9805-11ea-9991-dcaf485e1536.jpg)
![20200517060427_1](https://user-images.githubusercontent.com/1235520/82135662-70073380-9805-11ea-83ff-a575b2bd5f16.jpg)
https://pastebin.com/wmgeqB2z

**Comment by Wyqer** [comment]
Temporary file as replacement for `scripts\server\sector\fn_sectorMonitor.fsm` to fix this issue. Needs to be unpacked before, of course. GitHub didn't accept *.fsm endings for file upload.

[fn_sectorMonitor.zip](https://github.com/KillahPotatoes/KP-Liberation/files/4639858/fn_sectorMonitor.zip)

**Comment by Wyqer** [comment]
Updated above zip, redownload if already downloaded.

**Comment by Elgin675** [comment]
Same issue for us yesterday !

**Comment by Nopus64** [comment]
Hi Wyqer,
just to get it right. Is the Updated `fn_sectorMonitor.fsm` already implementet in all missions?
We got the bug also now quite a lot on Takistan.

**Comment by Wyqer** [comment]
No, it's not in the released files. The above zip is holding the fixed file.
