### ISSUE TITLE
[0.96.7] Zeus module not properly initialized

### ISSUE THREAD

**Issue by Shane130798** [KillahPotatoes/KP-Liberation#791]
### Basic Information

**Mission version:**
0.97.7
**Map used:**
Takistan, Malden 2035, Alitis
**Mods used:**
Just Simplex Services
**Dedicated or local game:**
Local Host
**Source of the mission file (URL):**

https://steamcommunity.com/sharedfiles/filedetails/?id=878715681&searchtext=kp+liberation
### Individual Things
**Did you edit anything within the mission files?**
No

**If yes, what did you edit exactly?**

N/A
### Short Issue Description
When in-game with no changes made to preferences except limited Zeus disabled, go to Zeus to add a pilot to the choppers at the base, then go to add "Simplex Transport module" to the unit or any other unit, simplex is either greyed out or Just doesn't do anything when clicking on the unit, Simplex still works with older versions of the KP (0.97.6) and outside of KP liberations (just stock maps with Zeus enabled). Tested on another computer the same issue persists.

### Expected Behaviour

You get the prompt to add a Service

**Comment by Shane130798** [comment]
Sorry about missing the Template!

**Comment by Wyqer** [comment]
Not mission related, as there is no "supports 3rd party script XYZ". So contact the creator of that script. We won't and can't provide support for these things. Beside of the fact that I've never heard of the script you try to use there. First thought is, that you just made a mistake in adding the script.

**Comment by Shane130798** [comment]
It's not a script for the game, its a mod:
https://steamcommunity.com/sharedfiles/filedetails/?id=1850026051&searchtext=simplex

**Comment by Wyqer** [comment]
We'll look into it concerning initialization of Zeus modules added by mods.

**Comment by Shane130798** [comment]
Thanks a lot, Really enjoy your misisons!
