### ISSUE TITLE
"Error: no unit" in permissions list

### ISSUE THREAD

**Issue by bux** [KillahPotatoes/KP-Liberation#792]
### Basic Information

**Mission version:**
v0.96.7

**Map used:**
Altis

**Mods used:**
![image](https://user-images.githubusercontent.com/1235520/82135582-9d9fad00-9804-11ea-8dd8-5f6bb12452b1.png)

**Dedicated or local game:**
Dedicated

**Source of the mission file (URL):**

https://github.com/KillahPotatoes/KP-Liberation/releases

### Individual Things
**Did you edit anything within the mission files?**
Params, Uniforms of player slots

### Short Issue Description
An erroneous unit gets added to the permission list

### Steps to Reproduce the Issue

n/a

### Screenshots, Serverlog or any other helpful Information
![image](https://user-images.githubusercontent.com/1235520/82550620-1bdeb500-9b5f-11ea-8172-1e293886b2ac.png)

**Comment by Wyqer** [comment]
Could you provide the content of the `GRLIB_permissions` variable of a campaign where you discovered this entry?

**Comment by bux** [comment]
Sent as PM

**Comment by bux** [comment]
Deleting the entry is not enough. It is reappearing after a while.
`["","Error: No unit",[true,false,false,false,false,true]]`
