### ISSUE TITLE
FOB Deleted on server restart or mission restart

### ISSUE THREAD

**Issue by EmperorJosh** [KillahPotatoes/KP-Liberation#800]
### Basic Information
So, the T90 used in the RHS AFRF is bugged because of a T14 Track or something making a hardkill trigger making it invincible. Rather than report the bug to you, because of its RHS's issue. I decided to remove it from the template and maybe add in some cup stuff to supplement its removal. I also changed the sector capture size and the fob size in a small amount so I could build FOB closer to the airfields and have fixed-wing frames. 

I load the new PBO on the server and it deleted all my placed assets for the FOB I had, I expected something like that. No biggie, so I made a new one. Well my server went through its restart and the FOB that was built now was deleted. 

So anything that is placed by us in the build mode is deleted, including the FOB building itself anytime the server is shutdown or the mission isnt active. 

**Map used:**
Tanoa
**Mods used:**
RHS Suite
F-18
HAFM
CUP
CBA
**Dedicated or local game:**
Dedicated
**Source of the mission file (URL):**
Steam release // KP Liberation Tanoa

### Individual Things
**Did you edit anything within the mission files?**
Yeah. 

**If yes, what did you edit exactly?**
As mentioned above, I've added Zeus, I made Zeus have access to all items. I've added some stuff to the RHS AFRF OPFOR template. I removed the T-90. I set the sector capture radius to 150 and the FOB build radius to 150. 

### Short Issue Description
FOB area and placed buildings, items, vehicles are deleted once the server is reset. All of them, placed by the build menu in the FOB build area are missing. 

### Expected Behaviour
When the server is turned back on or the missions is reselected to play, the FOB's buildings, Items and Vehicles should be there. 

### Steps to Reproduce the Issue
Started server, started mission, placed items. Waited 5 minutes, shut mission down, reloaded mission, items are gone. 

### Screenshots, Serverlog or any other helpful Information
12:04:00   Error position: <_classnamesToSave) &&                   >
12:04:00   Error Undefined variable in expression: _classnamestosave
12:04:00 File mpmissions\__cur_mp.Tanoa\scripts\server\game\save_manager.sqf..., line 547
12:04:00 Error in expression <ob_range * 2)) select {
((typeof _x) in _classnamesToSave) &&               

Seems to be relevant. I can provide a bigger log if need.

**Comment by Wyqer** [comment]
That's not irrelevant, that's your issue. You made a mistake in your edits. For this kind of support join the Discord server, as it's no bug in the framework. Recheck your edits.
