### ISSUE TITLE
Server/HC performance counters overlay visible in Micro DAGR

### ISSUE THREAD

**Issue by bux** [KillahPotatoes/KP-Liberation#801]
### Basic Information

**Mission version:**
v0.96.7

**Map used:**
Altis

**Mods used:**
![image](https://user-images.githubusercontent.com/1235520/82135582-9d9fad00-9804-11ea-8dd8-5f6bb12452b1.png)

**Dedicated or local game:**
Dedicated

**Source of the mission file (URL):**

https://github.com/KillahPotatoes/KP-Liberation/releases

### Individual Things
**Did you edit anything within the mission files?**
Params, Uniforms of player slots
Added the fix from #788

### Short Issue Description
The added markers showing the current performance of the server and each used HC are visible in the microDAGR compass view.

### Steps to Reproduce the Issue

* Have an microDAGR
* Open ACE's microDAGR compass view

### Screenshots, Serverlog or any other helpful Information
![20200527191002_1](https://user-images.githubusercontent.com/1235520/83101169-ff3c0300-a0b1-11ea-94cf-01af33157768.jpg)

**Comment by Wyqer** [comment]
That's weird. Does the micro dagr displays the lower left corner of the map or something? Some kind of funny, too.
Why would map markers appear on this particular ACE item? 🤔

**Comment by bux** [comment]
![image](https://user-images.githubusercontent.com/1235520/83101944-c00eb180-a0b3-11ea-9c80-9f43cf2fc9fc.png)
![image](https://user-images.githubusercontent.com/1235520/83101956-c6049280-a0b3-11ea-8817-63c5be2e706d.png)

**Comment by Wyqer** [comment]
Already thought that this should be addressed by ACE instead of creating a workaround for one mod item in the framework.
Still something I would've never expected to see/happen 😄

**Comment by veteran29** [comment]
Yet again Liberation is finding ACE "bugs" :grimacing:

**Comment by Wyqer** [comment]
As it will be worked on by ACE itself, I'll close this here for now.
