### ISSUE TITLE
Sling Load Assist (SLA) doesn't drive the SLA MFD window

### ISSUE THREAD

**Issue by RG-Sneaker** [KillahPotatoes/KP-Liberation#802]
### Basic Information
**Mission version:**
96.7
**Map used:**
GM Weferlingen Summer
**Mods used:**
CBA_A3, ShackTac User Interface, Tao Folding Map, Enhanced Soundscape, Advanced Rappelling, Advanced Sling Loading, Advanced Towing, Advanced Urban Rappelling, Enhanced Movement, BWMod, FA18 Super Hornet, Immerse, JSRS SOUNDMOD, RHSAFRF, RHSUSAF, Suppress, KP Ranks, RHSGREF, LEN-Cold War Aircraft
**Dedicated or local game:**
Dedicated
**Source of the mission file (URL):**
https://github.com/KillahPotatoes/KP-Liberation/releases/download/v0.96.7/kp_liberation.gm_weferlingen_summer.zip

### Individual Things
**Did you edit anything within the mission files?**
Yes

**If yes, what did you edit exactly?**

mission_params.hpp |  
-- | --
STR_A3_RequiredTrait | STR_A3_RequiredTrait_MedicSpeedMultiplier
STR_A3_RequiredItems |  
CleanupVehicles 4 |  
Fatigue 0 |  
RespawnCooldown 300 |  
  |  
kp_liberation_config.sqf |  
KP_liberation_cr_wounded_chance 95 |  
KP_liberation_cr_wounded_gain 5 |  

### Expected Behaviour
I expect "liftable objects" markers such as FOB Containers to appear in the SLA MFD

### Steps to Reproduce the Issue
I repackaged a FOB ('A') to a container and tried to lift it using a heli with Sling and SLA, but the SLA MFD showed no liftable object markers - only the grid and the legend as if the SLA MFD was not actually running.

**Comment by Wyqer** [comment]
Wasn't able to reproduce this issue.
Recheck if you haven't edited the classnames or some of your used mods are interfere with this.
With just GM loaded and the default summer preset, there are no issues with repack the FOB as container and lift it via slingloading. Showing fine in the SLA MFD.
