### ISSUE TITLE
Civlil informant is not being registered at an FOB

### ISSUE THREAD

**Issue by nicoman35** [KillahPotatoes/KP-Liberation#807]
### Basic Information

**Mission version:** v0.96.7
**Map used:** Altis, but is irrelevant
**Mods used:** irrelevant
**Dedicated or local game:** Local game, but irrelevant
**Source of the mission file (URL):** https://github.com/nicoman35/KP-Liberation

### Individual Things
**Did you edit anything within the mission files?**
A lot of things, but irrelevant to this bug

**If yes, what did you edit exactly?**
see above

### Short Issue Description
When trying to bring the civil informant to an FOB, he will just stay there, without being registered at the FOB.
This is because of a missing '};' inside the script 
KP-Liberation\Missionframework\scripts\client\civinformant\civinfo_escort.sqf
look here in my fork, where I corrected the bug:
https://github.com/nicoman35/KP-Liberation/commit/3215fdf94b2c3fc0f3749bc56ae54125b36eb16b?diff=unified

### Expected Behaviour
the civilist should be ungrouped and give information, which will never happen, because the responsible civinfo_escort.sqf will be ended without an error due to the missing };

### Steps to Reproduce the Issue

irrelevant

**Comment by Wyqer** [comment]
Creating a pull request with this one would've been easier, I guess.
Anyway, it's fixed and thanks for investigation of the issue. 👍

**Comment by nicoman35** [comment]
I would have loved to open a pull request. But my fork is now 24 commits ahead of the master, and afaik, there is no way to make a pull request including just one commit. I tried, but it wanted to pull every commit I made.

**Comment by Wyqer** [comment]
I recommend to keep the master of your fork in sync, while having your group specific adjustments in an own branch. That way you can always get the updates in your fork, move them to your "play branch" and you will still be able to create "PR branches" from your fork master. That way you can always create proper PRs, if you would like to contribute anything.
Just if you think about adjusting your workflow in your fork and/or think you might contribute anything in the future via PRs.
