### ISSUE TITLE
Build weapons / add equipment to buildable items

### ISSUE THREAD

**Issue by Methos752** [KillahPotatoes/KP-Liberation#808]
So, I've looked everywhere for a solution to this before asking here.  I want the ability to buy/build rifles for my team with increasing cost.  For example, start out building recruits with no weapons, then buy/build individual weapons for each.  At start we may only have enough for some Enfields so equip with those, steal some off dead enemy soldiers as we go.  Later as supplies are increased, buy some Garands or some AR15s.  The point is to be able to upgrade the current team weapons without spawning entirely new units.  I'm open to spawning individual rifles or a weapons box with a stack or a truck with a stack.  So far, nothing has worked.

So, I tried adding the weapons directly to the buildable items list (presets\blufor\custom) as follows:

buildings = [
        ["Weapon_hlc_rifle_Bushmaster300",0,50,0],                                 //AR15

When in game, it shows up in the build list and when I select it, it appears on the ground but when I click,"build" it confirms the items was built but it disappears.  I've changed vehicles in this way before so I know the process works, just don't understand why the rifle doesn't.

I've also tried using a custom (ALiVE Orbat made) truck and to load them in it's init section but even the default vehicles I'm finding have their equipment storage emptied.  Is this in a Liberation script somewhere that all vehicles cargo is removed?

The ideal would be to buy/build a weapon box with x number of a particular rifle in them but that has me completely baffled.  I'm able to spawn in the physical weapons box no problem, it's getting the items preloaded that eludes me.  Also, I added this to the buildings section

["Box_NATO_Wps_F",0,0,0],

and it spawns the object but, it's empty.  Doesn't even contain the default items.  ???

Thanks for any thoughts on this.

**Comment by Methos752** [comment]
No reply, no comment - just, "invalid" and closed it.  Nice.  Idiot....

**Comment by zardock** [comment]
Hey method, I can’t really help you with your idea, I don’t think it’s an issue more an new feature ldea. But I was interested, yes there is a function which clears the cargo of all spawned objects. But it has a parameter to turn it off? But I don’t how 😅. 

https://github.com/KillahPotatoes/KP-Liberation/blob/master/Missionframework/functions/fn_clearCargo.sqf

Also you are not really kind... everybody is doing stuff here in their free Time...

**Comment by Methos752** [comment]
Labeling a thread "invalid" and closing it without a response or reason
why, THAT is "not really kind."

**Comment by Dubjunk** [comment]
It's closed and invalid because we've an issue template that you didn't use.
