### ISSUE TITLE
Enemy Units converting to Civilians

### ISSUE THREAD

**Issue by GrupoPhoenix** [KillahPotatoes/KP-Liberation#809]
## Bug report
Basic information:

Version 0.96.7

Map: Chernarus

ACE, ACEX, RHS USAF, RHS AFRF, RHS GREF, Compatibility.

The bug ocurs on dedicated server.
Only change presets for blufor and opfor.

The bug happens when approach to some enemy location, the Units spawn correctly, but sometimes the enemy units appears in civilian side.

![unit](https://user-images.githubusercontent.com/54595107/86511795-a839f400-bdfc-11ea-8ca1-ccd53546d5f7.jpg)

**Comment by Dubjunk** [comment]
Please use the full issue template for your report, as we'll need some more informations about the bug.
We don't know if you maybe used an edited reupload or something.
