### ISSUE TITLE
Capturing surrendered enemies not possible even after merging fixes

### ISSUE THREAD

**Issue by LunaticManiac** [KillahPotatoes/KP-Liberation#816]
## Bug report
I already submitted it here: https://github.com/KillahPotatoes/KP-Liberation/issues/815
But I didn't fill the form correctly.
### Basic Information
**Mission version:**
0.96.7
**Map used:**
Livonia
**Mods used:**
ace | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=463939057
ACE Compat - RHS Armed Forces of the Russian Federation | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=773131200
ACE Compat - RHS United States Armed Forces | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=773125288
ACE Compat - RHS: GREF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=884966711
ACRE2 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=751965892
CBA_A3 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
JSRS SOUNDMOD | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=861133494
RHSAFRF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843425103
RHSGREF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843593391
RHSSAF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843632231
RHSUSAF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843577117
**Dedicated or local game:**
local game: Host can, others don't
dedicated: No one can do it
**Source of the mission file (URL):**
N/A yet

### Individual Things
**Did you edit anything within the mission files?**
Yes
**If yes, what did you edit exactly?**
I merged:
https://github.com/KillahPotatoes/KP-Liberation/commit/a6fb990a9484e97147f6105bb7b31518748308f9
and
https://github.com/KillahPotatoes/KP-Liberation/commit/ee0124decaf9fd39984af24fb093f3b396b1d23b
to my local copy of liberation
### Short Issue Description
The enemy joins our group after capturing him, but doesn't put the hands down or move, if the player doing isn't the host of the game.

### Expected Behaviour
the captured soldier follows us

### Steps to Reproduce the Issue
I tried to capture surrendering enemies a lot of times.

### Screenshots, Serverlog or any other helpful Information
According to this page: https://ace3mod.com/wiki/framework/events-framework.html
"Event handlers in ACE3 are implemented through CBA’s Event System. They should be used to trigger or allow triggering of specific functionality."
the event "ace_captives_setSurrendered" should be called instead of the ace function directly.
Note: the "ace_captiveStatusChanged" is a different event, called by the function we talked about in previous ticket.

use

["ace_captives_setSurrendered",[_unit,true],_unit] call CBA_fnc_targetEvent;
and
["ace_captives_setSurrendered",[_unit,false],_unit] call CBA_fnc_targetEvent;

instead of 

[_unit, true] call ACE_captives_fnc_setSurrendered;
and
[_unit, false] call ACE_captives_fnc_setSurrendered;

I don't want to create a Pull Request as my local git is a bit broken and I don't want to fix it for this ticket and I didn't need github for years.

**Comment by Wyqer** [comment]
> The enemy joins our group after capturing him, but doesn't put the hands down or move

Well, that's a new perspective, of course. Good you used the template now.
We're also playing with ACE and when getting POWs we ziptie them, use the capture action and then we escort them via ACE. So not bothering with commanding them as group member.
So with your description the issue might be that due to joining your group, the AI is of course changing his locality and therefore the function call on the server won't do what it should be anymore, because the argument isn't local anymore. Sounds senseful and in that case it needs to be changed.
Will verify this issue on our weekly session this evening. 👍
