### ISSUE TITLE
Disable radio usage when unconscious

### ISSUE THREAD

**Issue by mplorentz** [KillahPotatoes/KP-Liberation#817]
### Is your feature request related to a problem? Please describe: 

When teammates are unconscious they are still able to talk over the radio when using Task Force Radio. This breaks some of the realism TFAR is designed to introduce.

### Describe the solution you'd like:

I'd like it if KP Liberation disabled the usage of TFAR radios for a player when they are unconsicous using the BI revive system.

### Additional context:

[Here](https://github.com/A3Antistasi/A3-Antistasi/blob/f643aafd31017803b87dfafec6c4628445a22cbf/A3-Antistasi/Revive/inconsciente.sqf#L82) is how Antistasi implemented this feature and [here](https://github.com/kcgrimes/grimes-simple-revive/commit/ccadce791a2322adf12027295d7dab936b80989c#diff-953e53487a632af39d7207abb23385c8R273) is how Grimes Revive script does it. I know it may not be as simple here since KP supports 2 or 3 different revive modes. But it looks like ACE already has this [implemented](https://github.com/acemod/ACE3/pull/4334/files)?

**Comment by Pi123263** [comment]
That sounds like something that TFAR should implement and not KP as a gamemode.

**Comment by Wyqer** [comment]
Yeah, that's nothing I would see in Liberation code. That would be something TFAR would need to work on.
The framework of Liberation isn't the correct place to provide compatibility/adjustments between 2 systems which aren't from the framework (TFAR and BI Revive in this case).
You could create an issue on the TFAR Repository and also mention this ticket there as reference, for example.
