### ISSUE TITLE
Attempting to Build vehicles listed in "KPLIB_b_vehToUnlock" throw script error in game.

### ISSUE THREAD

**Issue by ahtotaat** [KillahPotatoes/KP-Liberation#841]
### Basic Information

**Mission version:**
0.96.8 dev
**Map used:**
kp_liberation.Enoch      (Livonia)
**Mods used:**
BLUFOR presets 0 and 30
**Dedicated or local game:**
Both
**Source of the mission file (URL):**

Upstream. Downloaded ZIP from Github (KP-Liberation-0.96.8.zip), went to Documents, Arma3 profile folder, mpmissions, created kp_liberation.Enoch, copied into latter content of the zip from /Missionframework and single mission file from /Missionbasefiles/kp_liberation.Enoch. Then started the game, opened Editor, opened mission and tested it against previous savegame that contained conquered air field, enough resources and infrastructure.

### Individual Things
**Did you edit anything within the mission files?**
No. I discovered issue while I was adding BLUFOR preset to my own fork. Upon seeing error, tested it against upstream code without any modifications of my own (excepting a change in BLUFOR preset integer for test in KPLIB_config.sqf)

**If yes, what did you edit exactly?**

### Short Issue Description
When I try to build vehicles llisted in KPLIB_b_vehToUnlock array I see black "window" appear in game with script error. Also vehicles that should not be "unlocked" due listed location being not conquered are listed as unlocked.

### Expected Behaviour
Expected behaviour: No script error window. Vehicles listed in KPLIB_b_vehToUnlock array should remain locked when associated military base is still
in enemy hands.

### Steps to Reproduce the Issue
Run the mission file with presets 0 or 30. It may be present with other BLUFOR presets as well - I simply havent tested against other presets. 
I should mention that functionality works with code from "master" branch, so I'd guess bug is caused by variable renaming somewhere in 0.96.8 branch.

### Screenshots, Serverlog or any other helpful Information
First screenshot with CUP/BWMod also loaded, second screenshot is with pure vanilla Contact
![Arma3_x64_2020_10_15_13_02_35_628](https://user-images.githubusercontent.com/7769694/96111243-a0084f00-0ee9-11eb-9f89-bab4c44c214c.png)
![Arma3_x64_2020_10_15_13_31_06_438](https://user-images.githubusercontent.com/7769694/96112075-be227f00-0eea-11eb-9313-ee98eb70abca.png)

**Comment by Wyqer** [comment]
Yeah, that's a missed replacement after the variable renaming with prefixes etc.
.8 isn't considered stable or playable atm. We've still to do exactly this to see if we don't missed something somewhere. But this report also spares us the time which would be needed to discover that particular one, so thanks for this, of course.

> I discovered issue while I was adding BLUFOR preset to my own fork

Guess we can then look forward to a PR from your side with new presets you want to contribute for .8?

**Comment by ahtotaat** [comment]
Ok, thanks.
> Guess we can then look forward to a PR from your side with new presets you want to contribute for .8?

Yeah, once I feel comfortable with the uniformity of the preset.

**Comment by veteran29** [comment]
Fixed on v0.96.8 in 28c19bb3e07991ca0039dd431fc9a780d2f4e796
