### ISSUE TITLE
"Custom Settings" from the .pbo

### ISSUE THREAD

**Issue by Failiatus** [KillahPotatoes/KP-Liberation#855]
Hey,
I just spent quite a while, actually way too long trying to apply my Custom settings to this great Game mode. 

Since I set up the Server to only play with 3-4 friends I wanted to adjust the difficulty and therefore used the Custom settings layout from the [Biki](https://community.bistudio.com/wiki/Arma_3:_Difficulty_Menu) to adjust them, but they would never apply. I could set Recruit, Regular, Veteran and it was no Problem but Custom? Nope. 

At some point I suspected  that the forced difficulty "Custom" must've been drawn from somewhere else than the .Arma3Profile.
So I ended up renaming the class Custom to "FUCK" 

> class FUCK
> 	{
> 		displayName = $STR_Difficulty_Custom;		// Name of the difficulty preset.
> 		optionDescription = "";						// Description
> 		optionPicture = "\A3\Ui_f\data\Logos\arma3_white_ca.paa"; // Picture
> 		levelAI = "AILevelLow";				    	// Level of AI skill

And then adjusted the forced difficulty in the Server Config.

> // MISSIONS CYCLE
> forcedDifficulty = "FUCK";
> 
> class Missions
> {
>     class kp_liberation
>     {
>         template = "kp_liberation.Altis";
>         difficulty = "FUCK";
>     };
> };
> 

And oh dear, oh dear it worked. 

I think it's a great thing you offer the ideal settings for this Game mode, but I couldn't find the settings in the .pbo and also no mention of it in any ReadMe or Github post, maybe I was blind, unlucky or whatever but I think it would be great if you could mention it or rename that part in the pbo file and adjust the suggested difficulty settings "Custom" Name, to spare people in the future from it.

Best regards,
Fail

**Comment by MildlyInterested** [comment]
You couldn't find any mention about any ideal settings that you have to overwrite cause they aren't any.
This is my setup which works just fine:
.Arma3Profile
```class DifficultyPresets
{
	class CustomDifficulty
	{
		class Options
		{
			reducedDamage=0;
			groupIndicators=2;
			friendlyTags=1;
			enemyTags=0;
			detectedMines=1;
			commands=1;
			waypoints=1;
			tacticalPing=1;
			weaponInfo=2;
			stanceIndicator=2;
			staminaBar=1;
			weaponCrosshair=1;
			visionAid=0;
			thirdPersonView=1;
			cameraShake=1;
			scoreTable=1;
			deathMessages=1;
			vonID=1;
			mapContentFriendly=1;
			mapContentEnemy=1;
			mapContentMines=1;
			autoReport=0;
			multipleSaves=0;
		};
		aiLevelPreset=3;
	};
	class CustomAILevel
	{
		skillAI=0.5;
		precisionAI=0.5;
	};
};
sceneComplexity=400000;
shadowZDistance=100;
viewDistance=1000;
preferredObjectViewDistance=800;
terrainGrid=25;
volumeCD=10;
volumeFX=10;
volumeSpeech=10;
volumeVoN=10;
singleVoice=0;
maxSamplesPlayed=96;
vonRecThreshold=0.029999999;
```

and this being the mission roster in my server_config.cfg:

```
class Missions
{
    class kp_liberation
    {
        template = "KP20Liberation20Lythium.lythium";
        difficulty = "custom";
    };
};```

**Comment by Failiatus** [comment]
Thanks for your Response. 
I used the difficulty template I linked from the Biki in the OP. 
The only difference I could find is that your .Arma3Profile uses the term "CustomDifficulty" while my template uses "Custom", weirdly enough that didn't work. Even though I see no reason why it shouldn't.

**Comment by MildlyInterested** [comment]
Did you read this part in your linked page?
