### ISSUE TITLE
Mission fails to start and teleport players to Carrier w/ custom factions

### ISSUE THREAD

**Issue by SpartanModding** [KillahPotatoes/KP-Liberation#887]
### Basic Information

**Mission version: 0.96.7a**

**Map used: Tanoa**

**Mods used: Advanced Urban Rappelling, ASR AI3, CBA_A3, Enhanced Movement, Enhanced Movement Rework, L3-GPNVG18 Panoramic Night Vision, NOD Colorize, Operation TREBUCHET, Project SFX: Remastered, Real Engine, RHSAFRF, RHSUSAF**
**All mods (except Operation TREBUCHET) tested and working in separate Liberation Tanoa without OPTRE**

**Dedicated or local game: Dedicated**

**Source of the mission file (URL): modified >** [*https://github.com/KillahPotatoes/KP-Liberation/releases/download/v0.96.7a/kp_liberation.Tanoa.zip*](url)

### Individual Things
**Did you edit anything within the mission files?**

Yes

**If yes, what did you edit exactly?**

Custom factions, custom parameters, custom server config

### Short Issue Description

Mods appear to be working, but upon mission start players aren't teleported to the carrier, the scrollwheel menu doesn't show, and the start of game UI fails to show. My guess is an issue with the custom faction, as all the other mods work perfectly in another Liberation instance.

### Expected Behaviour

The mission should start.

### Steps to Reproduce the Issue

Make custom UNSC and URF factions, upload to server, mission breaks, cry.
(All modified files and server log attached)

### Screenshots, Serverlog or any other helpful Information
[Liberation broke.zip](https://github.com/KillahPotatoes/KP-Liberation/files/6935572/Liberation.broke.zip)

**Comment by MildlyInterested** [comment]
join discord and ask for help, the mission is fine you simply got the syntax wrong in your `custom.sqf` preset.

**Comment by SpartanModding** [comment]
> join discord and ask for help, the mission is fine you simply got the syntax wrong in your `custom.sqf` preset.

Thank you, I couldn't find it.
