### ISSUE TITLE
Feature Suggestion: Enemy boats. :ok_hand:

### ISSUE THREAD

**Issue by Applejakerie** [KillahPotatoes/KP-Liberation#90]
Enemy boats and a reason for 'em too. 👍

**Comment by FatRefrigerator** [comment]
I think it'd be really cool to have boats patrolling

**Comment by Wyqer** [comment]
Will have a look into that, as it's not only "add boat classnames". But yeah, some checks if surface is water etc. and it should be working quite nice.
Will be something for 0.96 then.

**Comment by Applejakerie** [comment]
Some kind of 'does sector overlap into water (not ponds or lakes) if so add boats to the spawns above water' or 'is friendly sector within 100m of coast, if so enemy could attack (and land a small force) via water'. I think would be my vote.

**Comment by nifewavinsycho** [comment]
I think this would be great as ive edited tanoa with multiple mods for the build menu.... mainly transport ships but also frigates and corvettes I think this will look really cool if they tried to attack my transport craft and my frigate blows it the hell out of the water hehe

**Comment by dvdbrewster** [comment]
boats are a cool idea
