### ISSUE TITLE
Players stuck on spawn island

### ISSUE THREAD

**Issue by bunkerbrohoxha** [KillahPotatoes/KP-Liberation#900]
Once players join our server they remain stuck on the initial spawn island, the server doesn't spawn them on the carrier nor does it offer the spawn menu. I haven't installed any mods and I can't figure out what's wrong. 
We're playing KP Liberation Altis.
How do I fix this?

**Server log**

> 14:55:02 Unsupported language English in stringtable
14:55:02 mpmissions\kp_liberation.Altis: string @STR_MISSION_TITLE cannot be localized client-side - move to global stringtable
14:55:02 Unsupported language English in stringtable
14:55:02  ➥ Context: mpmissions\__cur_mp.Altis\stringtable.xml
14:55:02 @STR_MISSION_TITLE: string @STR_MISSION_TITLE cannot be localized client-side - move to global stringtable
14:55:02 CTI 34 KP Liberation Altis v0.96.7a: string @STR_MISSION_DESCRIPTION cannot be localized client-side - move to global stringtable
14:55:02 Mission kp_liberation.Altis: Number of roles (37) is different from 'description.ext::Header::maxPlayer' (34)
14:55:02 Starting mission:
14:55:02  Mission file: kp_liberation (__cur_mp)
14:55:02  Mission world: Altis
14:55:02  Mission directory: mpmissions\__cur_mp.Altis\
14:55:05 Strange convex component202 in a3\structures_f\households\house_small01\d_house_small_01_v1_f.p3d:geometryView
14:55:05 Strange convex component203 in a3\structures_f\households\house_small01\d_house_small_01_v1_f.p3d:geometryView
14:55:06 Strange convex component145 in a3\plants_f\tree\t_pinuss2s_b_f.p3d:geometryView
14:55:06 Strange convex component149 in a3\plants_f\tree\t_pinuss2s_b_f.p3d:geometryView
14:55:06 Strange convex component115 in a3\structures_f\households\house_big01\u_house_big_01_v1_f.p3d:geometryView
14:55:06 Strange convex component117 in a3\structures_f\households\house_big01\u_house_big_01_v1_f.p3d:geometryView
14:55:08 "TCAGame/BIS_fnc_log: [BIS_fnc_preload] ----- Initializing scripts in kp_liberation -----"
14:55:08 "TCAGame/BIS_fnc_log: [recompile] recompile BIS_fnc_missionTasksLocal"
14:55:08 "TCAGame/BIS_fnc_log: [recompile] recompile BIS_fnc_missionConversationsLocal"
14:55:08 "TCAGame/BIS_fnc_log: [recompile] recompile BIS_fnc_missionFlow"
14:55:08 "TCAGame/BIS_fnc_log: [preInit] BIS_fnc_feedbackMain (0 ms)"
14:55:08 "TCAGame/BIS_fnc_log: [preInit] BIS_fnc_missionHandlers (0 ms)"
14:55:08 "TCAGame/BIS_fnc_log: [preInit] BIS_fnc_storeParamsValues (0.999451 ms)"
14:55:08 "TCAGame/BIS_fnc_log: [preInit] ""DeltaTime computation started"""
14:55:08 "TCAGame/BIS_fnc_log: [preInit] BIS_fnc_keyframeAnimation_deltaTime (0 ms)"
14:55:08 "TCAGame/BIS_fnc_log: [preInit] BIS_fnc_getServerVariable (0 ms)"
14:55:08 "TCAGame/BIS_fnc_log: [preInit] BIS_fnc_OM_HandleMapControls (0 ms)"
14:55:08 "TCAGame/BIS_fnc_log: [BIS_fnc_OM_moduleSmartMarkers] Error: SmartMarker system has not been yet initialized."
14:55:08 "TCAGame/BIS_fnc_log: [preInit] BIS_fnc_OM_moduleSmartMarkers (0 ms)"
14:55:08 "TCAGame/BIS_fnc_log: [preInit] KPPLM_fnc_preInit (0 ms)"
14:55:08 Strange convex component16 in a3\boat_f_jets\carrier_01\carrier_01_hull_05_2_f.p3d:geometry
14:55:08 Strange convex component17 in a3\boat_f_jets\carrier_01\carrier_01_hull_05_2_f.p3d:geometry
14:55:08 Strange convex component197 in a3\boat_f_jets\carrier_01\carrier_01_hull_06_2_f.p3d:geometryFire
14:55:08 Strange convex component199 in a3\boat_f_jets\carrier_01\carrier_01_hull_06_2_f.p3d:geometryFire
14:55:08 Strange convex component41 in a3\boat_f_jets\carrier_01\carrier_01_hull_09_1_f.p3d:geometryView
14:55:08 Strange convex component42 in a3\boat_f_jets\carrier_01\carrier_01_hull_09_1_f.p3d:geometryView
14:55:08 Strange convex component43 in a3\boat_f_jets\carrier_01\carrier_01_hull_09_1_f.p3d:geometryView
14:55:08 Strange convex component44 in a3\boat_f_jets\carrier_01\carrier_01_hull_09_1_f.p3d:geometryView
14:55:08 Strange convex component45 in a3\boat_f_jets\carrier_01\carrier_01_hull_09_1_f.p3d:geometryView
14:55:08 Strange convex component46 in a3\boat_f_jets\carrier_01\carrier_01_hull_09_1_f.p3d:geometryView
14:55:09 [KPLIB] [PARAM] ----- Server starts parameter initialization
14:55:09 [KPLIB] [PARAM] Save/Load is set to LOAD
14:55:09 [KPLIB] [PARAM] --- Mission Options ---
14:55:09 [KPLIB] [PARAM] Unitcap: 4
14:55:09 [KPLIB] [PARAM] Difficulty: 2
14:55:09 [KPLIB] [PARAM] Aggressivity: 3
14:55:09 [KPLIB] [PARAM] AdaptToPlayercount: true
14:55:09 [KPLIB] [PARAM] Civilians: 0
14:55:09 [KPLIB] [PARAM] FirstFob: false
14:55:09 [KPLIB] [PARAM] FirstFobVehicle: false
14:55:09 [KPLIB] [PARAM] MaximumFobs: 26
14:55:09 [KPLIB] [PARAM] MaxSquadSize: 36
14:55:09 [KPLIB] [PARAM] BluforDefenders: true
14:55:09 [KPLIB] [PARAM] Autodanger: false
14:55:09 [KPLIB] [PARAM] DayDuration: 4
14:55:09 [KPLIB] [PARAM] ShorterNights: true
14:55:09 [KPLIB] [PARAM] Weather: 3
14:55:09 [KPLIB] [PARAM] VanillaFog: true
14:55:09 [KPLIB] [PARAM] ResourcesMultiplier: 5
14:55:09 [KPLIB] [PARAM] ArsenalType: false
14:55:09 [KPLIB] [PARAM] DirectArsenal: false
14:55:09 [KPLIB] [PARAM] PlayerMenu: true
14:55:09 [KPLIB] [PARAM] VictoryCondition: 1
14:55:09 [KPLIB] [PARAM] --- Revive Options ---
14:55:09 [KPLIB] [PARAM] ReviveMode: 1
14:55:09 [KPLIB] [PARAM] ReviveDuration: 6
14:55:09 [KPLIB] [PARAM] ReviveRequiredTrait: 0
14:55:09 [KPLIB] [PARAM] ReviveMedicSpeedMultiplier: 3
14:55:09 [KPLIB] [PARAM] ReviveRequiredItems: 2
14:55:09 [KPLIB] [PARAM] UnconsciousStateMode: 0
14:55:09 [KPLIB] [PARAM] ReviveBleedOutDuration: 180
14:55:09 [KPLIB] [PARAM] ReviveForceRespawnDuration: 3
14:55:09 [KPLIB] [PARAM] --- Gameplay Options ---
14:55:09 [KPLIB] [PARAM] Fatigue: false
14:55:09 [KPLIB] [PARAM] WeaponSway: false
14:55:09 [KPLIB] [PARAM] ArsenalUsePreset: false
14:55:09 [KPLIB] [PARAM] MapMarkers: true
14:55:09 [KPLIB] [PARAM] MobileRespawn: true
14:55:09 [KPLIB] [PARAM] RespawnCooldown: 0
14:55:09 Connected to Steam servers
14:55:09 [KPLIB] [PARAM] MobileArsenal: true
14:55:09 [KPLIB] [PARAM] AttackedSectorRespawn: false
14:55:09 [KPLIB] [PARAM] AiLogistics: true
14:55:09 [KPLIB] [PARAM] CR_Building: false
14:55:09 [KPLIB] [PARAM] HaloJump: 5
14:55:09 [KPLIB] [PARAM] ClearCargo: true
14:55:09 [KPLIB] [PARAM] AllowEnemiesInImmobile: 50
14:55:09 [KPLIB] [PARAM] DelayDespawnMax: 5
14:55:09 [KPLIB] [PARAM] LimitedZeus: false
14:55:09 [KPLIB] [PARAM] CommanderZeus: true
14:55:09 [KPLIB] [PARAM] ZeusAddEnemies: false
14:55:09 [KPLIB] [PARAM] HighCommand: true
14:55:09 [KPLIB] [PARAM] SuppMod: 1
14:55:09 [KPLIB] [PARAM] Tutorial: true
14:55:09 [KPLIB] [PARAM] --- Technical Options ---
14:55:09 [KPLIB] [PARAM] Permissions: true
14:55:09 [KPLIB] [PARAM] CleanupVehicles: 2
14:55:09 [KPLIB] [PARAM] Introduction: false
14:55:09 [KPLIB] [PARAM] DeploymentCinematic: false
14:55:09 [KPLIB] [PARAM] Whitelist: true
14:55:09 [KPLIB] [PARAM] ServerRestart: 0
14:55:09 [KPLIB] [PARAM] ----- Server finished parameter initialization - Time needed: 0.0480003 seconds
14:55:09 Error in expression <_O_V3S_Refuel_TKA",
"I_Truck_02_fuel_F"
"UK3CB_AAF_B_M977A4_Fuel",
"gm_gc_army_u>
14:55:09   Error position: <"UK3CB_AAF_B_M977A4_Fuel",
"gm_gc_army_u>
14:55:09   Error Missing ]
14:55:09 File mpmissions\__cur_mp.Altis\kp_liberation_config.sqf..., line 734
14:55:09 Error in expression <_O_V3S_Refuel_TKA",
"I_Truck_02_fuel_F"
"UK3CB_AAF_B_M977A4_Fuel",
"gm_gc_army_u>
14:55:09   Error position: <"UK3CB_AAF_B_M977A4_Fuel",
"gm_gc_army_u>
14:55:09   Error Missing ]
14:55:09 File mpmissions\__cur_mp.Altis\kp_liberation_config.sqf..., line 734
14:55:09 [KPLIB] [PRESETS] ----- Server starts preset initialization -----
14:55:09 [KPLIB] [PRESETS] Not found vehicles listed below are not an issue in general. It just sorts out vehicles from not loaded mods.
14:55:09 [KPLIB] [PRESETS] Only if you e.g. use a CUP preset and you get messages about missing CUP classes, then check your loaded mods.
14:55:09 Error in expression 
};
switch (KP_liberation_preset_blufor) do {
case  >
14:55:09   Error position: 
case  >
14:55:09   Error append: Undefined variable in expression: kp_liberation_preset_blufor
14:55:09 File mpmissions\__cur_mp.Altis\presets\init_presets.sqf..., line 11
14:55:09 c:\bis\source\stable\futura\lib\network\networkserver.cpp NetworkServer::OnClientStateChanged:NOT IMPLEMENTED - briefing!
14:55:09  Mission id: 3c1f4a16473f3002b6b60ba968922cc5bf36e947
14:55:09 Attempt to override final function - bis_fnc_storeparamsvalues_data
14:55:09 "TCAGame/BIS_fnc_log: [module] BIS_fnc_moduleCurator (66.9994 ms)"
14:55:09 "TCAGame/BIS_fnc_log: [module] BIS_fnc_moduleCuratorSetAttributes (42.9993 ms)"
14:55:09 "TCAGame/BIS_fnc_log: [module] BIS_fnc_moduleCuratorSetAttributes (42.9993 ms)"
14:55:09 "TCAGame/BIS_fnc_log: [module] BIS_fnc_moduleCuratorSetAttributes (42.9993 ms)"
14:55:09 "TCAGame/BIS_fnc_log: [script] initServer.sqf"
14:55:09 "TCAGame/BIS_fnc_log: [postInit] BIS_fnc_missionFlow (0 ms)"
14:55:09 "TCAGame/BIS_fnc_log: [postInit] BIS_fnc_initParams (2.00081 ms)"
14:55:09 "TCAGame/BIS_fnc_log: [postInit] BIS_fnc_initRespawn (0 ms)"
14:55:09 "TCAGame/BIS_fnc_log: [postInit] BIS_fnc_keyframeAnimation_init (1.9989 ms)"
14:55:09 "TCAGame/BIS_fnc_log: [postInit] BIS_fnc_reviveInit (0 ms)"
14:55:09 "TCAGame/BIS_fnc_log: [postInit] KPLIB_fnc_initCuratorHandlers (0 ms)"
14:55:09 "TCAGame/BIS_fnc_log: [BIS_fnc_preload] ----- Scripts initialized at 1335 ms -----"

**Comment by MildlyInterested** [comment]
You edited some preset and forgot/added a comma therefore breaking the syntax of the preset file which causes the whole mission to break.
See github FAQ, for more support please join the discord.
