### ISSUE TITLE
cant place here: there are 1 object(s) within 11 meters of construction

### ISSUE THREAD

**Issue by DanielPX1** [KillahPotatoes/KP-Liberation#938]
I cannot place anything because game takes me as an object

error: 
cant place here: there are 1 object(s) within 11 meters of construction

fix: build above you, but I have levitating storages and cars / planes explode from the fall once I build them above me ... destroys gameplay a lot. I met this issues on several maps (takistan... etc)

![obrazek](https://github.com/KillahPotatoes/KP-Liberation/assets/80678982/10248921-c59a-459f-b44c-5d0ccc12f1cd)

**Comment by MildlyInterested** [comment]
You have a mod that's attaching invisible objects to your player, usually 2nd rifle slot mods etc.
Either remove the mod, or disable the collision check in KP Liberation. 
How to here: https://gist.github.com/MildlyInterested/12a5d78536c82b273fc3c814990f8e5d#disable-collision-detection-on-building

**Comment by DanielPX1** [comment]
Thanks! Problem was "GGE: Weapon Swap" mod
