### ISSUE TITLE
The mission does not work, which can be seen in the map preview

### ISSUE THREAD

**Issue by kosmakkk** [KillahPotatoes/KP-Liberation#959]
### Basic Information

**Mission version:**
i think its 0.96.7

**Map used:**
Altis

**Mods used:**

**Dedicated or local game:**
local game

**Source of the mission file (URL):**
https://steamcommunity.com/sharedfiles/filedetails/?id=2821063037&searchtext=tcw+liberation

### Individual Things
**Did you edit anything within the mission files?**
Yes 

**If yes, what did you edit exactly?**
I unpacked the files in PBO so I could edit this mission in Eden editor and adapt it to play with friends

Yesterday we could still play normally, after the game I wanted to edit the reputation which is set incorrectly and prevents us from having fun, so I changed the first 5 lines in the kp_liberation_config.sqf file which are about civil reputation penalty, I set them to 0. I thought it was a problem, so later I changed it back to the numbers that were originally. But it still didn't fix the problem

### Short Issue Description
 the sector markers on the map are not sectors but ordinary signs, everything happens when you click continue in the lobby and go to the map view and then you can see that nothing works, so you don't even have to start the scenario

### Expected Behaviour

it looks like The PK script does not start, and it's just a map with sector markers, it doesn't even show the "Server fps" inscription in the lower left corner

### Steps to Reproduce the Issue

every time I want to run a mission

**Comment by some-evil-kitty** [comment]
Not an official KP Lib release.
